import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bearerToken, randomSessionToken, secureEqual, sha256Hex, validPin } from '../server/ready/auth-core.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
assert.equal(validPin('1234'), true);
assert.equal(validPin('123456'), true);
assert.equal(validPin('123'), false);
assert.equal(validPin('12a4'), false);
const sessionToken = randomSessionToken();
assert.match(sessionToken, /^[A-Za-z0-9_-]{43}$/);
assert.equal(bearerToken(`Bearer ${sessionToken}`), sessionToken);
assert.equal((await sha256Hex(sessionToken)).length, 64);
assert.equal(secureEqual('same-secret', 'same-secret'), true);
assert.equal(secureEqual('same-secret', 'other-secret'), false);

const sql = readFileSync(resolve(root, 'sql/ready_milestone_1.sql'), 'utf8');
assert.match(sql, /ready_questions[\s\S]*type text[\s\S]*payload jsonb/, 'Question is no longer generic JSON-backed data');
assert.match(sql, /ready_attempts_are_immutable[\s\S]*before update or delete/, 'Attempts are no longer append-only');
assert.match(sql, /grant all on table[\s\S]*ready_students[\s\S]*to service_role/, 'READY server role lacks table privileges');

const examSql = readFileSync(resolve(root, 'sql/ready_exam_refactor.sql'), 'utf8');
assert.match(examSql, /create table if not exists public\.ready_exams/, 'Exam table is missing');
assert.match(examSql, /add column if not exists exam_id/, 'Passage is not attached to an Exam');
assert.match(examSql, /add column if not exists school[\s\S]*add column if not exists grade/, 'Student school and grade are missing');
assert.match(examSql, /publication_id drop not null/, 'New attempts still require a Publication');
assert.match(examSql, /status in \('draft', 'available'\)/, 'Question availability state is missing');

const passageLibrarySql = readFileSync(resolve(root, 'sql/ready_passage_library_refactor.sql'), 'utf8');
assert.match(passageLibrarySql, /create table if not exists public\.ready_exam_passages/, 'Exam-to-Passage join table is missing');
assert.match(passageLibrarySql, /position integer not null/, 'Exam Passage order is missing');
assert.match(passageLibrarySql, /add column if not exists exam_id uuid/, 'Attempt Exam context is missing');
assert.match(passageLibrarySql, /disable trigger ready_attempts_no_update[\s\S]*enable trigger ready_attempts_no_update/, 'Attempt backfill does not restore append-only protection');

const authSql = readFileSync(resolve(root, 'sql/ready_auth_migration.sql'), 'utf8');
assert.match(authSql, /pin_hash = extensions\.crypt\(p_pin, pin_hash\)/, 'Student PIN is not verified against a password hash');
assert.match(authSql, /extensions\.crypt\(p_pin, extensions\.gen_salt\('bf'/, 'Student PIN is not stored as bcrypt');
assert.match(authSql, /ready_sessions[\s\S]*token_hash/, 'Opaque sessions are missing');
assert.doesNotMatch(authSql, /\bpin\s+text\s*(?:not null)?[,)]/i, 'A plaintext PIN column was added');
assert.match(authSql, /grant all on table public\.ready_sessions, public\.ready_login_attempts to service_role/, 'READY server role lacks auth-table privileges');

const edge = readFileSync(resolve(root, 'server/ready/index.ts'), 'utf8');
assert.doesNotMatch(edge, /READY_AI_PROVIDER|READY_AI_MODEL|ANTHROPIC_API_KEY|OPENAI_API_KEY|generateWithAnthropic|generateWithOpenAI|bakePassage|ready_apply_passage_bake/, 'READY Edge still has an AI bake/provider path');
assert.match(edge, /SUPABASE_SECRET_KEYS/, 'READY does not use Supabase server-side secret keys');
assert.match(edge, /authenticate\(req, "student"\)/, 'Student APIs do not require a student session');
assert.match(edge, /student_id: context\.student\.id/, 'Learning event identity does not come from the authenticated session');
assert.match(edge, /studentExamAccess/, 'Server does not check Exam access from the authenticated student');
assert.match(edge, /"school", student\.school[\s\S]*"grade", student\.grade/, 'Exam is not constrained by student school and grade');
assert.match(edge, /ready_exam_passages/, 'Runtime does not use the Exam-to-Passage relationship');
assert.match(edge, /exam_id: context\.examId/, 'Learning events do not retain verified Scope context');
assert.match(edge, /async function setScopePassages[\s\S]*ready_set_current_scope_passages/, 'Current Scope Passage range cannot be edited atomically');
assert.doesNotMatch(edge, /async function reorderPassages|reorder_passages/, 'Passage drag reorder remains in the runtime');
assert.match(edge, /studentPassageAccess[\s\S]*ready_word_lookup_events/, 'Passage Study events are not authenticated against Exam access');
assert.doesNotMatch(edge, /translateSentences|createPassageBatch|retryPassageStudy/, 'Legacy Passage AI/batch mutation paths remain active');
assert.match(edge, /sentenceRows/, 'Structured Passage writes do not preserve explicit sentence rows');
const createPassageBody = edge.match(/async function createPassage\(body: any\) \{[\s\S]*?\n\}/)?.[0] || '';
assert.match(createPassageBody, /ready_create_passage_with_sentences/, 'Structured rows are not saved through the atomic Passage RPC');
assert.doesNotMatch(createPassageBody, /splitSentences|translateSentences|preparePassageStudy/, 'Structured Passage writes still re-split or AI-process supplied rows');
assert.match(createPassageBody, /return \{ passageId \}/, 'Passage creation performs follow-up reads instead of returning the transaction id');
assert.match(edge, /async function deleteImpact[\s\S]*ready_attempts[\s\S]*ready_delete_student_cascade/, 'Student deletion does not report impact then cascade atomically');
assert.match(edge, /ready_delete_passage_cascade/, 'Passage deletion is not atomic');
assert.doesNotMatch(edge, /ready_publish_study_set|ready_publication_questions/, 'New READY runtime still depends on Publication');
assert.doesNotMatch(edge, /READY_TEACHER_KEY|x-ready-teacher-key/, 'Raw teacher secret authentication is still active');
assert.doesNotMatch(edge, /generate_order|student_questions|submit_attempt|update_question|set_question_status|delete_question/, 'Dormant Question/Attempt operations remain dispatched');
assert.doesNotMatch(edge, /function studentQuestions|function submitAttempt|function generateOrderQuestion/, 'Dormant ORDER runtime remains in the Edge Function');

const app = readFileSync(resolve(root, 'ready/app.js'), 'utf8');
const adminApp = readFileSync(resolve(root, 'ready/admin/app.js'), 'utf8');
const adminHtml = readFileSync(resolve(root, 'ready/admin/index.html'), 'utf8');
const readyCss = readFileSync(resolve(root, 'ready/ready.css'), 'utf8');
const readyConfig = readFileSync(resolve(root, 'ready/config.js'), 'utf8');
const atomicPassageSql = readFileSync(resolve(root, 'supabase/migrations/20260826155500_ready_atomic_passage_import.sql'), 'utf8');
const legacyDeleteSql = readFileSync(resolve(root, 'supabase/migrations/20260826174000_ready_legacy_delete_cleanup.sql'), 'utf8');
assert.match(atomicPassageSql, /ready_create_passage_with_sentences/, 'Atomic Passage import RPC is missing');
assert.match(atomicPassageSql, /insert into public\.ready_passages[\s\S]*insert into public\.ready_passage_sentences/, 'Passage and sentence rows are not in one database transaction');
assert.match(atomicPassageSql, /with ordinality/, 'Pasted row order is not preserved as sentence_index');
assert.doesNotMatch(app, /submit_attempt|data-order-move|student_questions/, 'ORDER UI remains in the Golden Path');
assert.doesNotMatch(adminApp + adminHtml, /question-editor|question-modal|v-analytics|renderAnalytics/, 'Dormant ORDER or Analytics UI remains in Admin');
assert.match(app, /student_bootstrap[\s\S]*renderScope/, 'Student does not enter the current Scope');
assert.match(app, /student_passage/, 'Student cannot open a Passage');
assert.match(app, /reading-passage/, 'Student Reader is missing');
assert.match(readyCss, /reading-passage\{display:grid;gap:14px/, 'Reader is not a sentence-card layout');
assert.match(readyCss, /reading-sentence\{display:block;padding:/, 'Reader sentences are not individual cards');
assert.match(app, /sentence-translation[\s\S]*data-save-sentence/, 'Sentence translation is not rendered inline beneath its card');
const openSentenceBody = app.match(/function openSentence\(sentenceEl\)\{[^\n]*\}/)?.[0] || '';
assert.match(openSentenceBody, /state\.activeSentenceId[\s\S]*renderReader/, 'Sentence interaction does not expand the inline card');
assert.doesNotMatch(openSentenceBody, /openSheet/, 'Sentence interaction still opens a separate sheet');
assert.match(readyCss, /--ready-sentence-saved[\s\S]*--ready-word-saved/, 'Sentence and word saved states do not have separate colors');
assert.match(app, /translation_view/, 'Stored teacher translations are not opened through an authenticated event');
assert.match(app, /sentenceSheet[\s\S]*sentence\.translation/, 'Sentence Sheet does not use the already-loaded translation');
assert.doesNotMatch(app, /sentenceBakes|analysis_snapshot|문장 구조|핵심 문법|핵심 표현/, 'Sentence sheet still depends on AI metadata');
assert.doesNotMatch(edge, /ready_sentence_bakes|structureSummary|grammarPoints|keyExpressions|analysis_snapshot/, 'Edge runtime still reads or writes sentence AI metadata');
assert.match(app, /record\('translation_view'/, 'Sentence view event is not recorded in the background');
assert.match(edge, /translate\.googleapis\.com[\s\S]*dt=bd/, 'On-demand Breeze-compatible dictionary candidates are missing');
assert.match(edge, /ready_saved_words[\s\S]*meaning_snapshot/, 'Selected word meaning is not stored in the simple SavedWord table');
assert.match(app, /savedWordLemmas[\s\S]*token\.lemma/, 'Saved-word highlights are not lemma based');
assert.match(app, /deleteLibraryItem[\s\S]*delete_saved_word[\s\S]*delete_saved_sentence/, 'Review saved items cannot be deleted');
assert.match(app, /breezeWordSheet[\s\S]*ready-lemma[\s\S]*ready-active-meaning[\s\S]*ready-sense-chips/, 'READY does not retain Breeze word-sheet hierarchy for lemma, meaning, and senses');
assert.match(app, /wordSheetLoading[\s\S]*wordSheetError/, 'READY word sheet has no Breeze-style loading and error states');
assert.match(app, /lexicalUsesSidePanel[\s\S]*presentLexical[\s\S]*ready-word-dock/, 'READY does not reuse Breeze’s side-panel versus bottom-sheet split');
assert.match(readyCss, /ready-word-side-open[\s\S]*ready-word-dock[\s\S]*flex:0 0 min\(340px,28vw\)/, 'Desktop dictionary still overlays rather than sharing the Reader layout');
assert.match(readyCss, /modal\[data-kind="lexical"\][\s\S]*max-height:72vh/, 'Touch dictionary is not capped as a Breeze-style bottom sheet');
assert.doesNotMatch(app + adminApp, /bake_passage|data-bake|Bake|rebake|bake_status|savedConceptIds|ready_lexical/, 'Frontend still exposes bake state or controls');
assert.match(app, /CACHE_INDEX[\s\S]*cachedPassage[\s\S]*cachePassage/, 'Passage Reader has no local read-through cache');
assert.match(app, /student-route="review"|studentRoute==='review'/, 'Student Review route is missing');
assert.match(app, /disabled aria-label="문제 유형 학습은 준비 중입니다"/, 'Unavailable question modes are not visibly disabled');
assert.doesNotMatch(app, /student_exam|renderExams|data-exam-id|data-back-exams/, 'Student Exam selection remains in the UI');
assert.doesNotMatch(app + adminApp, /studySetId|publicationId|publish_set/, 'Frontend still depends on StudySet or Publication');
assert.doesNotMatch(app, /main_idea|sentence_translation|vocabulary/, 'A future question type was implemented early');
assert.match(adminApp, /admin_login/, 'Admin session login is missing');
assert.match(adminApp, /student-school-filter[\s\S]*student-grade-filter/, 'Student school/grade filters are missing');
assert.doesNotMatch(adminApp, /confirmation.*DELETE|DELETE.*confirmation/, 'Typed DELETE confirmation remains in the UI');
assert.match(adminApp, /delete-actions[\s\S]*data-close-delete[\s\S]*type="submit">삭제/, 'READY delete confirmation modal is missing');
assert.match(adminApp, /data-set-scope/, 'Scope Passage checkbox editing is missing');
assert.match(adminApp, /data-open-scope-school[\s\S]*scope-detail-content[\s\S]*scope-passage-grid/, 'Scope cards do not open a full-page Passage editor');
assert.doesNotMatch(adminApp, /<details class="exam-range"/, 'Scope Passage editing still uses the cramped inline disclosure');
assert.match(adminApp, /data-select-passage[\s\S]*assign-passages-to-scope/, 'Passage checkbox to Scope assignment flow is missing');
assert.doesNotMatch(adminApp, /data-delete-scope|delete_scope/, 'Permanent Scope slots can be deleted');
assert.doesNotMatch(adminApp, /reorder_passages|draggedPassageId|draggable="true"/, 'Passage drag order remains in the UI');
assert.match(adminApp, /update-passage-form/, 'Passage editing is missing');
assert.doesNotMatch(adminApp + adminHtml, /parsePassageRows|renderImportPreview|passage-import-modal|create-passage-form|\btsv\b|PDF Import|DOCX Import/, 'READY still exposes an in-product Import workflow');
assert.match(adminHtml, /data-route="students"[\s\S]*data-route="passages"[\s\S]*data-route="scopes"/, 'Admin navigation order is incorrect');
assert.doesNotMatch(adminHtml, /create-exam-form|새 Exam|Exam 만들기/, 'Exam list view still exposes Exam creation');
assert.doesNotMatch(adminApp, /reorder_students|saveGroupOrder/, 'Student manual ordering remains in the admin UI');
assert.match(legacyDeleteSql, /to_regclass\('public\.ready_publication_questions'\)[\s\S]*delete from public\.ready_publication_questions/, 'Passage deletion does not clean retired Publication links');
assert.doesNotMatch(app + adminApp + readyConfig, /SUPABASE_SERVICE_ROLE_KEY|OPENAI_API_KEY|READY_ADMIN_PASSWORD|READY_TEACHER_KEY/, 'A server secret name/value leaked into frontend runtime code');

console.log('READY core checks passed');
