import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { runInNewContext } from 'node:vm';
import { bearerToken, randomSessionToken, secureEqual, sha256Hex, validPin } from '../server/ready/auth-core.mjs';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const read=path=>readFileSync(resolve(root,path),'utf8');

assert.equal(validPin('1234'),true);
assert.equal(validPin('123456'),true);
assert.equal(validPin('123'),false);
const token=randomSessionToken();
assert.match(token,/^[A-Za-z0-9_-]{43}$/);
assert.equal(bearerToken(`Bearer ${token}`),token);
assert.equal((await sha256Hex(token)).length,64);
assert.equal(secureEqual('same-secret','same-secret'),true);

const baseline=read('supabase/migrations/20260826150000_ready_current_baseline.sql');
const questionMigration=read('supabase/migrations/20260828150000_ready_question_first.sql');
const neRelinkMigration=read('supabase/migrations/20260830130000_ready_relink_ne_textbook_aliases.sql');
const edge=read('server/ready/index.ts');
const app=read('ready/app.js');
const css=read('ready/ready.css');
const extractor=read('tools/ready-extract-ne-minbyeongcheon.py');

assert.match(baseline,/ready_questions[\s\S]*type text[\s\S]*payload jsonb/,'Question must remain generic JSON-backed data');
assert.match(baseline,/ready_attempts_are_immutable[\s\S]*before update or delete/,'Attempts must remain append-only');
assert.match(questionMigration,/ready_import_question_bundle[\s\S]*jsonb_array_elements[\s\S]*return imported/,'Atomic bundle import is missing');
assert.match(questionMigration,/multiple_choice[\s\S]*written_response/,'Both deterministic response types are not indexed/importable');
assert.match(questionMigration,/source_question_no[\s\S]*section/,'Source identity is not validated');
assert.match(neRelinkMigration,/lesson\\s\*1[\s\S]*공통영어2[\s\S]*민병천[\s\S]*question_count desc/,'NE textbook aliases do not resolve to the question-bearing lesson');
assert.match(neRelinkMigration,/ready_exam_passages[\s\S]*surviving_passage_id[\s\S]*scope relink contract failed/,'NE scope relink is not atomic or verified');

assert.match(edge,/studentOps = new Set\(\["student_bootstrap", "student_passage", "student_questions", "student_review_questions", "submit_attempt"\]\)/,'Student runtime exposes operations outside the Question-first path');
assert.doesNotMatch(edge.match(/async function dispatch[\s\S]*?\n\}/)?.[0]||'',/word_lookup|save_word|save_sentence|personal_library/,'Dormant lexical operations remain dispatched');
assert.match(edge,/function publicQuestion[\s\S]*responseSlots[\s\S]*variantSegments[\s\S]*contentBlocks/,'Structured public Question contract is incomplete');
assert.doesNotMatch(edge.match(/function publicQuestion[\s\S]*?\n\}/)?.[0]||'',/accepted_answers|payload\.answer/,'Public Question exposes grading data');
assert.match(edge,/type === "multiple_choice"[\s\S]*selected\.length === answer\.length[\s\S]*selected\.every/,'MCQ grading is not deterministic set equality');
assert.match(edge,/type === "written_response"|question\.type === "written_response"/,'Written response grading is missing');
assert.match(edge,/normalize\("NFKC"\)[\s\S]*toLowerCase\(\)[\s\S]*replace\(\/\\s\+\/g/,'Written normalization is incomplete');
assert.match(edge,/accepted_response_sets[\s\S]*acceptedSets\.some/,'Linked written-response combinations are not graded atomically');
assert.match(edge,/inlineOptionGroups[\s\S]*inlineSelected[\s\S]*inlineAnswer/,'Inline passage-option grading is missing');
assert.match(edge,/detectedGroups[\s\S]*choicesMatchGroups\(detectedGroups, choices\)/,'Inline options can leak from a shared Passage into choices that do not encode those groups');
assert.match(edge,/\[ⓐ-ⓩ\]\|\\\(\[A-H\]\\\)/,'Parenthesized inline option groups are missing');
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*123:[\s\S]*to hedge/,'Verified 23번 target repair is missing');
assert.match(edge,/\/요약\/\.test[\s\S]*sourceQuestionNo === 125 \? "vocabulary"/,'Summary prompts and 23번 vocabulary skill are not repaired');
assert.match(edge,/targetRanges[\s\S]*const interaction = "choices"/,'Passage metadata must point while MCQ answers stay in the plain choice list');
assert.match(edge,/choicesMatchGroups[\s\S]*inlineGroups[\s\S]*흐름상\|문맥상/,'Combination questions are not recognized from their own choices');
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*97:[\s\S]*to take part[\s\S]*is related/,'18번 밑줄 범위 repair is missing');
assert.match(edge,/canonicalText:"related"[\s\S]*canonicalText:"interested"/,'Deliberately transformed targets do not retain their canonical anchors');
assert.match(edge,/SUMMARY_REPAIRS[\s\S]*101:[\s\S]*137:/,'Imported summary material is not repaired for existing rows');
assert.match(edge,/CHOICE_PART_REPAIRS[\s\S]*119:[\s\S]*122:/,'Multi-column source choices are not structurally repaired');
assert.match(edge,/CHOICE_PART_REPAIRS[\s\S]*19:[\s\S]*23:[\s\S]*28:[\s\S]*35:/,'Section 1 combination choices are still visually concatenated');
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*118:[\s\S]*can define[\s\S]*the most[\s\S]*playing/,'22번 underline targets are not repaired');
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*128:[\s\S]*to reach[\s\S]*familiar[\s\S]*were/,'24번 grammar targets do not point to complete expressions');
assert.match(edge,/WRITING_GUIDE_REPAIRS[\s\S]*277:[\s\S]*300:[\s\S]*343:[\s\S]*350:/,'18~28 written questions do not expose structured task guides');
for(const questionNo of [...Array.from({length:24},(_,index)=>277+index),...Array.from({length:8},(_,index)=>343+index)])assert.match(edge,new RegExp(`\\b${questionNo}:`),`Section 4 question ${questionNo} has no explicit UI contract`);
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*295:[\s\S]*that glows in the Orion constellation[\s\S]*297:/,'Written Passage focus ranges are incomplete');
assert.match(edge,/TARGET_RANGE_REPAIRS[\s\S]*236:[\s\S]*bare imagination of a feast[\s\S]*240:[\s\S]*continued to explore/,'Meaning questions with label-only prompts lack their full source expressions');
assert.match(edge,/unresolvedQuestionIds[\s\S]*latest\.has[\s\S]*!correct/,'Review is not derived from the latest append-only Attempt');
assert.match(edge,/studentReviewQuestions[\s\S]*eligibleUnresolvedQuestionIds/,'Review queue endpoint is missing');
assert.match(edge,/isMainTextQuestion[\s\S]*isDialogueText[\s\S]*sourceBigrams/,'Textbook questions are not positively matched to the canonical main text');
assert.match(edge,/normalizeMainTextQuestionRows[\s\S]*refersToPrevious[\s\S]*currentMain/,'Legacy shared-passage state is not repaired before filtering');
assert.match(edge,/attemptedQuestionIds[\s\S]*!attempted\.has/,'Solved questions are not removed from the new-question queue');
assert.match(edge,/cleanQuestionText[\s\S]*물음에\\s\*답하시오/,'Worksheet directions can still leak into the passage');
assert.match(edge,/setScopePassages[\s\S]*ready_relink_ne_minbyeongcheon_lessons[\s\S]*importQuestions[\s\S]*ready_relink_ne_minbyeongcheon_lessons/,'Scope changes and question imports do not repair textbook aliases');
assert.match(edge,/legacyWorkbook[\s\S]*publicStoredWritingGuide[\s\S]*CHOICE_PART_REPAIRS/,'Workbook-specific repairs are not scoped by source identity');
assert.match(edge,/setText: cleanQuestionText\(payload\.set_text[\s\S]*setId: clean\(payload\.source\.set_id/,'Question-set passage identity is not exposed to the student UI');

assert.match(app,/function renderReader[\s\S]*plainPassage/,'Reader does not render continuous prose');
assert.doesNotMatch(app,/openLexical|openSentence|translation_view|save_sentence|savedWord|savedSentence/,'Lexical/sentence study remains connected to the student frontend');
assert.match(app,/family\|\|'standard'[\s\S]*questionPassageHtml/,'Question family renderer is missing');
assert.match(app,/contentBlocks/,'Structured Passage blocks are not rendered');
assert.match(app,/setBasePassage[\s\S]*summaryText/,'Stable Passage variants and summary blocks are not rendered');
assert.match(app,/responseType==='written'[\s\S]*data-written-slot/,'Written response UI is missing');
assert.match(app,/writingGuideHtml[\s\S]*writing-conditions[\s\S]*writing-bank/,'Writing conditions and word bank are not separated from the prompt');
assert.match(app,/written-workspace correction[\s\S]*고친 말만 입력/,'Correction questions are not presented as expression-to-answer tasks');
assert.match(app,/sentence-answer[\s\S]*textarea[\s\S]*완성한 영어 문장/,'Sentence completion does not provide a usable writing area');
assert.match(app,/writtenSlotsHtml[\s\S]*multi-correction[\s\S]*summary-slots/,'Multi-slot summary and correction tasks are still flattened into one field');
assert.match(app,/writingGuide\?\.title\|\|question\.prompt/,'Flattened PDF prompts still override structured writing titles');
assert.match(app,/questionSetKey[\s\S]*question-set-nav[\s\S]*data-question-index/,'Passage question-set navigation is missing');
assert.match(app,/question\.source[\s\S]*source\?\.setId[\s\S]*source-set:/,'Question sets do not use the source-scoped set identity');
assert.match(app,/setBasePassage[\s\S]*question\.setText/,'Question sets do not prefer their immutable worksheet context');
assert.match(app,/function setBasePassage[\s\S]*function currentQuestionPassage[\s\S]*function questionPassageHtml/,'A question set does not keep an immutable base Passage with current-question overlays');
assert.match(app,/applyAlternativeOverlay[\s\S]*applyTargetOverlay[\s\S]*applyStructuralOverlay[\s\S]*pointedPassageHtml/,'Question overlays are not isolated by interaction type');
assert.match(app,/target\.canonicalText\|\|target\.text/,'Target overlays cannot distinguish source anchors from displayed expressions');
assert.match(app,/\['implication','order'\]\.includes\(question\.skill\)[\s\S]*question\.variantText/,'Standalone implication and order questions do not use their explicit question material');
assert.match(app,/worksheetPassageText[\s\S]*questionSetIndices\(session\)\.length>1[\s\S]*setBasePassage/,'Question sets do not preserve one original worksheet Passage');
assert.match(app,/canonicalOption[\s\S]*sort\(\(a,b\)=>b\.length-a\.length\)/,'Overlapping alternatives do not prefer the specific longer option');
assert.match(app,/passage-pointer[\s\S]*question-footnote/,'Plain Passage pointing and footnote rendering is missing');
assert.match(app,/markQuestionChoice[\s\S]*choiceSwipe[\s\S]*pointerdown[\s\S]*pointermove/,'Choice candidate swipe states are missing');
assert.match(app,/combinationChoiceParts[\s\S]*choice-separator/,'Grammar and vocabulary combination choices are not visually separated');
assert.match(app,/inactiveVariantText[\s\S]*question\.interaction!==['"]inline_options['"][\s\S]*canonicalHasOption/,'Inactive annotations are not cleaned when moving within a question set');

const passageFunctionNames=['canonicalHasOption','canonicalOption','resolvedSetPassageText','labelNeedleIndex','replaceNeedle','maskBlank','worksheetPassageText','setBasePassage','applyAlternativeOverlay','applyTargetOverlay','structuralMarkerPositions','applyStructuralOverlay','currentQuestionPassage','questionSetKey','questionSetIndices'];
const passageFunctions=passageFunctionNames.map(name=>app.match(new RegExp(`function ${name}\\([^\\n]+`))?.[0]||'').join('\n');
const canonical18='Dear students, The annual Riverdale Science Fair will be held on July 18 with the theme Sustainable Future. Although we announced the fair last month, student registration is still lower than expected. Therefore, we would like to encourage more of you to take part. You are invited to present a project. You will have the opportunity to showcase your work. If you are interested, please submit a description. We look forward to your participation.';
const worksheet18='Dear students, The annual Riverdale Science Fair will ⓐ[hold / be held] on July 18 with the theme “㉠________.” (A) Although we announced the fair last month, student registration is still lower than expected. (B) You are ⓑ[inviting / invited] to present a project. (C) You will have the opportunity ⓒ[showcase / to showcase] your work. (D) If you are interested, please submit a description. (E) We look forward to your participation.';
const sharedSource={passageNo:18,section:'1',questionNo:1};
const setQuestions=[
  {skill:'grammar',passageText:canonical18,variantText:worksheet18,inlineGroups:[{label:'ⓐ',options:['hold','be held']},{label:'ⓑ',options:['inviting','invited']},{label:'ⓒ',options:['showcase','to showcase']}],source:sharedSource},
  {skill:'blank',choices:['Space Tourism','Sustainable Future'],passageText:canonical18,variantText:worksheet18,source:sharedSource},
  {skill:'insertion',stimulus:'Therefore, we would like to encourage more of you to take part.',passageText:canonical18,variantText:worksheet18,source:sharedSource},
  {skill:'content',passageText:canonical18,variantText:worksheet18,source:sharedSource},
];
const setSession={items:setQuestions.map((question,index)=>({question:{...question,id:`set-${index}`}})),index:0};
const basePassages=setQuestions.map((_question,index)=>runInNewContext(`${passageFunctions}; setBasePassage(session)`,{session:{...setSession,index}}));
assert.equal(new Set(basePassages).size,1,'The same question set does not share one immutable base Passage');
assert.doesNotMatch(basePassages[0],/Therefore, we would like/,'Insertion stimulus remains in the set base Passage');
assert.match(basePassages[0],/㉠_{4,}/,'The shared blank was not preserved in the set base Passage');
assert.match(basePassages[0],/ⓐhold \/ be held[\s\S]*\(A\)[\s\S]*\(E\)/,'The original worksheet apparatus is not preserved as the set master');
const overlayFor=index=>runInNewContext(`${passageFunctions}; currentQuestionPassage(session,session.items[session.index].question)`,{session:{...setSession,index}});
assert.match(overlayFor(0),/ⓐhold \/ be held[\s\S]*ⓑinviting \/ invited[\s\S]*ⓒshowcase \/ to showcase/,'Grammar alternatives are not presented without revealing the answer');
assert.match(overlayFor(2),/\(A\)[\s\S]*\(B\)[\s\S]*\(C\)[\s\S]*\(D\)[\s\S]*\(E\)/,'Insertion positions are missing from the insertion question');
assert.equal(new Set(setQuestions.map((_question,index)=>overlayFor(index))).size,1,'A set question changes the original worksheet Passage between tabs');
const targetCanonical='You are invited to present a model related to conservation. If you are interested, please submit it.';
const transformedTarget={skill:'grammar',passageText:targetCanonical,variantText:targetCanonical,targetRanges:[{label:'ⓒ',text:'is related',canonicalText:'related'},{label:'ⓓ',text:'interesting',canonicalText:'interested'}],source:sharedSource};
const transformedSession={items:[{question:{...transformedTarget,id:'target-transform'}}],index:0};
assert.match(runInNewContext(`${passageFunctions}; currentQuestionPassage(session,session.items[0].question)`,{session:transformedSession}),/ⓒis related[\s\S]*ⓓinteresting/,'Variant-only target expressions cannot be anchored to canonical prose');
const implication={skill:'implication',passageText:'Canonical prose without a label.',variantText:'Context. (A)encourage more of you to take part. Ending.',source:{passageNo:18,section:'3',questionNo:233}};
const implicationSession={items:[{question:{...implication,id:'implication'}}],index:0};
assert.match(runInNewContext(`${passageFunctions}; currentQuestionPassage(session,session.items[0].question)`,{session:implicationSession}),/\(A\)encourage more of you to take part/,'Implication question loses its explicit underlined expression');
const orderQuestion={skill:'order',passageText:'Canonical prose.',variantText:'Opening. (A) First block. (B) Second block. (C) Third block.',source:{passageNo:18,section:'3',questionNo:255}};
const orderSession={items:[{question:{...orderQuestion,id:'order'}}],index:0};
assert.match(runInNewContext(`${passageFunctions}; currentQuestionPassage(session,session.items[0].question)`,{session:orderSession}),/\(A\)[\s\S]*\(B\)[\s\S]*\(C\)/,'Order question loses its explicit A/B/C blocks');
assert.doesNotMatch(app.match(/function renderScope\(\)[\s\S]*?\n\}/)?.[0]||'',/data-open-review/,'Home still duplicates the top-level wrong-answer review route');
assert.match(app,/student_review_questions[\s\S]*복습 문제/,'Wrong-answer review UI is missing');
assert.match(app,/resultFeedbackHtml[\s\S]*data-toggle-answer[\s\S]*data-toggle-explanation/,'Wrong answers do not reveal the answer and explanation progressively');
assert.match(app,/readerParagraphs[\s\S]*study-back/,'Focused study navigation or paragraph Reader is missing');
assert.doesNotMatch(app,/function continuationQuestion|class="start-study"|class="home-tabs"/,'Home still exposes quick-start or study-mode tabs');
assert.match(app,/function exitQuestions[\s\S]*loadDashboard/,'Leaving a question session can show a stale Review count');
assert.match(css,/Question-first reset[\s\S]*reading-passage\{[\s\S]*display:block/,'Reader prose reset is missing');
assert.match(css,/question-block\.group[\s\S]*question-segment\.blank[\s\S]*written-response/,'Question family styling is incomplete');
assert.match(css,/written-workspace\.correction[\s\S]*writing-conditions[\s\S]*writing-bank/,'Structured writing workspace styling is incomplete');
assert.match(css,/correction-reference[\s\S]*written-slot-list/,'Complex correction and summary answers do not have readable field layouts');
assert.match(css,/@media\(max-width:700px\)[\s\S]*written-workspace\.correction\{grid-template-columns:1fr\}/,'Writing correction cards do not stack on mobile');
assert.match(css,/passage-pointer[\s\S]*question-set-nav/,'Question-set pointing styling is missing');
assert.match(css,/passage-blank[\s\S]*white-space:nowrap/,'Inline blanks can still expand into an awkward wrapped bar');
assert.match(css,/question-choice\.eliminated[\s\S]*question-choice\.candidate/,'Choice deliberation states are missing');
assert.match(css,/font-size:16px!important/,'iOS Safari input zoom prevention is missing');
assert.match(css,/body\.study-mode #topbar\{display:none\}[\s\S]*\.study-back/,'Study mode still exposes the global top bar');
assert.match(extractor,/payload\["source_kind"\]\s*=\s*source_kind/,'Textbook import does not persist source boundaries');
for(const kind of ['textbook_main','dialogue','supplemental'])assert.match(extractor,new RegExp(`"${kind}"`),`Textbook source kind ${kind} is missing`);
assert.match(extractor,/current_context = source_before_conditions/,'A new written-response passage does not update the following shared context');
assert.match(css,/reader-shell>\.question-prompt\{[^}]*clamp\(18px,1\.65vw,22px\)/,'Question prompt has regressed to an oversized display heading');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/stimulus[\s\S]*target_ranges[\s\S]*city_tour_blocks/,'Question-set source repairs are missing from the importer');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/\("요약", "summary"\)[\s\S]*\("빈칸", "blank"\)/,'Summary questions are still misclassified as generic blanks');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/family == "summary"[\s\S]*summary_text/,'Summary material is not imported explicitly');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/TABLE_CHOICE_PARTS[\s\S]*119:[\s\S]*122:/,'Importer still flattens multi-column choices into ambiguous strings');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/TABLE_CHOICE_PARTS[\s\S]*19:[\s\S]*23:[\s\S]*28:[\s\S]*35:/,'Importer still flattens Section 1 grammar columns');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/question_no == 128[\s\S]*"text": "to reach"/,'Importer does not preserve the full 24번 grammar target');
assert.match(readFileSync('tools/ready-extract-exam4you-mcq.py','utf8'),/TARGET_RANGE_REPAIRS[\s\S]*102:[\s\S]*133:[\s\S]*240:/,'Importer lacks verified full-expression underline spans');

console.log('READY Question-first core checks passed');
