import { readyApi } from '../api.js';
import { parsePassageRows, validatePassageRows } from './import-core.mjs';

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const SESSION_KEY = 'ready-admin-session';
const state = { token:'', data:null, route:'students', editor:null, passageEditorId:null, analyticsExamId:null, deleteTarget:null, passagePage:0, selectedPassageIds:new Set(), importDraft:null };
let busyCount = 0, toastTimer;
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
const formatDate = value => value ? new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)) : '—';
function setBusy(on, label='잠시만요…') { busyCount=Math.max(0,busyCount+(on?1:-1)); $('#busy').hidden=!busyCount; $('#busy span:last-child').textContent=label; }
function toast(message) { $('#toast').textContent=message; $('#toast').classList.add('on'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').classList.remove('on'),3200); }
function applyTheme(theme) { const dark=theme==='dark'; document.documentElement.classList.toggle('dark',dark); document.body.classList.toggle('dark',dark); localStorage.setItem('ready-theme',theme); }
function clearSession() { sessionStorage.removeItem(SESSION_KEY); state.token=''; state.data=null; }
async function call(op,data={},token=state.token,label='잠시만요…') { setBusy(true,label); try{return await readyApi(op,data,token);}finally{setBusy(false);} }
async function safely(job,{auth=true}={}) { try{return await job();}catch(error){if(auth&&error.status===401){clearSession();showLogin();}toast(error.message||'요청을 처리하지 못했습니다.');return null;} }
function showLogin() { $('#admin-login').hidden=false; $('#admin-nav').hidden=true; $('#admin-logout').hidden=true; $$('.view').forEach(view=>view.classList.remove('on')); }
function route(name) { state.route=name; $$('.view').forEach(view=>view.classList.toggle('on',view.id===`v-${name}`)); $$('.navbtn').forEach(button=>button.classList.toggle('on',button.dataset.route===name)); if(name==='analytics')renderAnalytics(); }
async function login(form) { const password=new FormData(form).get('password'); const data=await safely(()=>call('admin_login',{password},'','관리자 비밀번호를 확인하는 중…'),{auth:false}); form.reset(); if(!data)return; state.token=data.session.token; sessionStorage.setItem(SESSION_KEY,JSON.stringify(data.session)); await loadAdmin(); }
async function loadAdmin() { const data=await safely(()=>call('teacher_bootstrap',{},state.token,'관리자 화면을 불러오는 중…')); if(!data)return; state.data=data; $('#admin-login').hidden=true; $('#admin-nav').hidden=false; $('#admin-logout').hidden=false; renderStudents(); renderPassages(); renderExams(); route(state.route); }
async function logout() { if(state.token)await safely(()=>call('logout')); clearSession(); showLogin(); }
function questionsFor(passageId){return state.data.questions.filter(question=>question.passage_id===passageId);}
function passagesForExam(examId){const byId=new Map(state.data.passages.map(passage=>[passage.id,passage]));return state.data.examPassages.filter(link=>link.exam_id===examId).sort((a,b)=>a.position-b.position).map(link=>byId.get(link.passage_id)).filter(Boolean);}
function passageFor(questionId){const q=state.data.questions.find(item=>item.id===questionId);return state.data.passages.find(item=>item.id===q?.passage_id);}

function renderStudents() {
  const school=$('#student-school-filter')?.value||'',grade=$('#student-grade-filter')?.value||'';
  const students=state.data.students.filter(student=>(!school||student.school===school)&&(!grade||student.grade===grade));
  const root=$('#admin-students');
  root.innerHTML=students.length?`<div class="table-wrap student-table"><table><thead><tr><th>이름</th><th>학교 / 학년</th><th>PIN 변경</th><th></th></tr></thead><tbody>${students.map(student=>`<tr><td><strong>${escapeHtml(student.name)}</strong></td><td>${escapeHtml(student.school)} · ${escapeHtml(student.grade)}</td><td><form class="pin-reset" data-reset-pin="${student.id}"><input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4,6}" minlength="4" maxlength="6" autocomplete="new-password" placeholder="새 PIN" required><button class="button quiet small" type="submit">변경</button></form></td><td><button class="button danger small" type="button" data-delete-student="${student.id}">삭제</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">조건에 맞는 학생이 없습니다.</div>';
}
function renderPassageSelection(){
  const root=$('#passage-selection'), selected=state.data.passages.filter(p=>state.selectedPassageIds.has(p.id)); if(!root)return;
  if(!selected.length){root.innerHTML='';return;}
  const grades=[...new Set(selected.map(p=>p.grade))], mixed=grades.length!==1;
  root.innerHTML=`<section class="card passage-selection"><div class="selection-summary"><strong>${selected.length}개 지문 선택</strong><button class="button quiet small" type="button" data-clear-passage-selection>선택 해제</button></div>${mixed?'<div class="result bad">같은 학년 지문만 하나의 시험범위로 만들 수 있습니다.</div>':`<form id="create-exam-from-passages" class="form-grid exam-create"><label><span>학교</span><select name="school" required><option>신흥고</option><option>동고</option><option>중앙고</option><option>한빛고</option></select></label><label><span>학년</span><input name="grade" value="${escapeHtml(grades[0])}" readonly></label><label><span>시험명</span><input name="title" maxlength="120" placeholder="2학기 중간고사" required></label><label><span>설명</span><input name="description" maxlength="500" placeholder="선택 사항"></label><button class="button primary" type="submit">선택한 지문으로 시험범위 만들기</button></form>`}</section>`;
}
function renderPassages(){const root=$('#passage-library');if(!root)return;const validIds=new Set(state.data.passages.map(p=>p.id));state.selectedPassageIds=new Set([...state.selectedPassageIds].filter(id=>validIds.has(id)));const grade=$('#passage-grade-filter')?.value||'',type=$('#passage-type-filter')?.value||'',year=$('#passage-year-filter')?.value||'',month=$('#passage-month-filter')?.value||'';const rows=state.data.passages.filter(p=>(!grade||p.grade===grade)&&(!type||p.source_type===type)&&(!year||String(p.source_year)===year)&&(!month||String(p.source_month)===month));const pageSize=15,totalPages=Math.max(1,Math.ceil(rows.length/pageSize));state.passagePage=Math.min(state.passagePage,totalPages-1);const page=rows.slice(state.passagePage*pageSize,(state.passagePage+1)*pageSize);root.innerHTML=`<p class="library-note">지문을 체크해 시험범위를 만드세요.</p><div class="table-wrap"><table><thead><tr><th>선택</th><th>제목</th><th>종류</th><th>학년</th><th>출처</th><th>문제</th><th></th></tr></thead><tbody>${page.map(p=>`<tr data-passage-row="${p.id}"><td><input class="passage-check" type="checkbox" aria-label="${escapeHtml(p.title)} 선택" data-select-passage="${p.id}" ${state.selectedPassageIds.has(p.id)?'checked':''}></td><td><button class="text-button" data-edit-passage="${p.id}">${escapeHtml(p.title)}</button></td><td>${p.source_type==='MOCK_EXAM'?'모의고사':'교과서'}</td><td>${escapeHtml(p.grade)}</td><td>${escapeHtml([p.source_year,p.source_month&&p.source_month+'월',p.source_label].filter(Boolean).join(' · ')||'—')}</td><td>${questionsFor(p.id).length}</td><td><button class="button quiet small" data-edit-passage="${p.id}">수정</button><button class="button danger small" data-delete-passage="${p.id}">삭제</button></td></tr>`).join('')||'<tr><td colspan="7">조건에 맞는 지문이 없습니다.</td></tr>'}</tbody></table></div><div class="pagination"><button class="button quiet small" data-passage-page="prev" ${state.passagePage===0?'disabled':''}>← Prev</button><span>${state.passagePage+1} / ${totalPages}</span><button class="button quiet small" data-passage-page="next" ${state.passagePage===totalPages-1?'disabled':''}>Next →</button></div>`;renderPassageSelection();}
function openPassage(passageId){const passage=state.data.passages.find(item=>item.id===passageId);if(!passage)return;state.passageEditorId=passageId;const sentenceCount=state.data.sentences.filter(item=>item.passage_id===passageId).length;$('#passage-editor').innerHTML=`<form id="update-passage-form"><div class="form-grid"><label><span>제목</span><input name="title" value="${escapeHtml(passage.title)}" required></label><label><span>종류</span><select name="sourceType"><option value="TEXTBOOK" ${passage.source_type==='TEXTBOOK'?'selected':''}>교과서</option><option value="MOCK_EXAM" ${passage.source_type==='MOCK_EXAM'?'selected':''}>모의고사</option></select></label><label><span>학년</span><select name="grade">${['1학년','2학년','3학년'].map(value=>`<option ${passage.grade===value?'selected':''}>${value}</option>`).join('')}</select></label><label><span>연도</span><input name="sourceYear" value="${passage.source_year||''}"></label><label><span>월</span><input name="sourceMonth" value="${passage.source_month||''}"></label></div><p class="lead compact">저장된 문장 ${sentenceCount}개 · 문장/해석은 등록 시 확정한 행을 그대로 사용합니다.</p><button class="button primary" type="submit">지문 정보 저장</button></form>`;$('#passage-modal').classList.add('on');$('#passage-modal').setAttribute('aria-hidden','false');}
function closePassage(){$('#passage-modal').classList.remove('on');$('#passage-modal').setAttribute('aria-hidden','true');state.passageEditorId=null;}
function renderExams() {
  const root=$('#teacher-exams');
  root.innerHTML=`<div class="exam-list">${state.data.exams.map(exam=>{const passages=passagesForExam(exam.id),included=new Set(passages.map(p=>p.id)),count=passages.reduce((sum,p)=>sum+questionsFor(p.id).length,0);return `<section class="card teacher-set"><div class="card-head"><div><p class="eyebrow">${escapeHtml(exam.school)} · ${escapeHtml(exam.grade)}</p><h2>${escapeHtml(exam.title)}</h2><p class="lead compact">지문 ${passages.length}개 · 문제 ${count}개</p></div><button class="button danger small" type="button" data-delete-exam="${exam.id}">Exam 삭제</button></div><div class="passage-list">${passages.map((p,index)=>`<div class="recent-row"><span>${index+1}. ${escapeHtml(p.title)}</span><strong>${questionsFor(p.id).length}문제</strong></div>`).join('')||'<div class="empty">포함된 지문이 없습니다.</div>'}</div><details class="exam-range"><summary>시험범위 지문 수정</summary><form data-update-exam="${exam.id}" class="exam-passage-picker"><p class="lead compact">체크한 지문만 이 Exam에 포함됩니다. 지문 라이브러리의 기본 순서가 시험 안의 순서로 저장됩니다.</p>${state.data.passages.map(p=>`<label class="check-row"><input type="checkbox" name="passageIds" value="${p.id}" ${included.has(p.id)?'checked':''}><span>${escapeHtml(p.grade)} · ${escapeHtml(p.title)} <small>${questionsFor(p.id).length}문제</small></span></label>`).join('')}<button class="button primary small" type="submit">시험범위 저장</button></form></details></section>`;}).join('')||'<div class="empty">아직 Exam이 없습니다.</div>'}</div>`;
}
function renderPassage(passage) {
  const sentences=state.data.sentences.filter(sentence=>sentence.passage_id===passage.id), questions=questionsFor(passage.id);
  return `<article class="passage"><div class="passage-head"><div><h3>${escapeHtml(passage.title)}</h3><p>${sentences.length} sentences · 원문 ID 고정</p></div><form class="actions" data-generate-passage="${passage.id}"><select name="difficulty">${[1,2,3,4].map(level=>`<option value="${level}">Level ${level}</option>`).join('')}</select><button class="button quiet small" type="submit">문제 추가</button></form></div>${questions.map(question=>`<div class="question-row"><div><span class="pill ${question.status==='available'?'good':'warn'}">${question.status}</span> <strong>ORDER · Level ${question.difficulty}</strong><div class="meta">${question.payload.chunks.length} chunks · generation ${question.generation}</div></div><div class="actions"><button class="button quiet small" type="button" data-preview-question="${question.id}">Preview</button>${question.status==='draft'?`<button class="button primary small" type="button" data-question-status="${question.id}" data-status="available">Available 승인</button>`:`<button class="button quiet small" type="button" data-question-status="${question.id}" data-status="draft">Draft로 전환</button>`}<button class="button danger small" type="button" data-delete-question="${question.id}">삭제</button></div></div>`).join('')}</article>`;
}

function openEditor(questionId) { const question=state.data.questions.find(item=>item.id===questionId); if(!question)return; const order=question.payload.correctOrder.map(id=>question.payload.chunks.find(chunk=>chunk.id===id)).filter(Boolean); state.editor={questionId,passageId:question.passage_id,difficulty:question.difficulty,chunks:structuredClone(order)}; renderEditor(); $('#question-modal').classList.add('on'); $('#question-modal').setAttribute('aria-hidden','false'); }
function closeEditor() { $('#question-modal').classList.remove('on'); $('#question-modal').setAttribute('aria-hidden','true'); state.editor=null; }
function renderEditor() { const editor=state.editor, question=state.data.questions.find(item=>item.id===editor.questionId); $('#question-editor').innerHTML=`<div class="editor-note">정답 순서와 문구를 검수합니다. Available 승인 순간, 해당 학교·학년 학생에게 보입니다.</div><div class="chunk-list">${editor.chunks.map((chunk,index)=>`<div class="chunk-edit" data-editor-chunk="${escapeHtml(chunk.id)}"><div class="chunk-number">${index+1}</div><textarea>${escapeHtml(chunk.text)}</textarea><div class="move-stack"><button type="button" data-editor-move="up" ${index===0?'disabled':''}>↑</button><button type="button" data-editor-move="down" ${index===editor.chunks.length-1?'disabled':''}>↓</button></div></div>`).join('')}</div><div class="editor-actions"><button class="button primary" type="button" data-save-question>수정 저장</button><button class="button quiet" type="button" data-regenerate-question>AI 다시 생성</button><button class="button ${question.status==='available'?'quiet':'primary'}" type="button" data-editor-approve>${question.status==='available'?'Draft로 전환':'Available 승인'}</button><button class="button danger" type="button" data-editor-delete>삭제</button></div>`; }
function captureEditor() { if(!state.editor)return; $$('[data-editor-chunk]').forEach(row=>{const chunk=state.editor.chunks.find(item=>item.id===row.dataset.editorChunk);if(chunk)chunk.text=row.querySelector('textarea').value.trim();}); }
async function saveEditor(){captureEditor();const payload={difficulty:state.editor.difficulty,chunks:state.editor.chunks,correctOrder:state.editor.chunks.map(chunk=>chunk.id)};const data=await safely(()=>call('update_question',{questionId:state.editor.questionId,payload},state.token,'문제를 저장하는 중…'));if(data){toast('수정 내용을 저장했습니다.');closeEditor();await loadAdmin();}}
async function setStatus(questionId,status){const data=await safely(()=>call('set_question_status',{questionId,status}));if(data){toast(status==='available'?'학생에게 문제를 열었습니다.':'문제를 Draft로 전환했습니다.');closeEditor();await loadAdmin();}}
async function removeQuestion(questionId){if(!confirm('이 문제를 삭제할까요?'))return;const data=await safely(()=>call('delete_question',{questionId}));if(data){closeEditor();await loadAdmin();}}
async function regenerate(){const editor=state.editor,data=await safely(()=>call('generate_order',{passageId:editor.passageId,difficulty:editor.difficulty,replaceQuestionId:editor.questionId},state.token,'AI가 의미 흐름을 분석하는 중…'));if(data){closeEditor();await loadAdmin();openEditor(data.question.id);}}

function questionIdsForExam(examId){return new Set(passagesForExam(examId).flatMap(p=>questionsFor(p.id).filter(q=>q.status==='available').map(q=>q.id)));}
function repeatedWrong(attempts){const count=new Map();attempts.filter(a=>!a.correct).forEach(a=>count.set(a.question_id,(count.get(a.question_id)||0)+1));return [...count.values()].filter(n=>n>=2).length;}
function renderAnalytics(){
  const root=$('#analytics-content'), exams=state.data.exams;if(!exams.length){root.innerHTML='<div class="empty">Exam을 만든 뒤 학습 기록을 확인할 수 있습니다.</div>';return;}if(!state.analyticsExamId||!exams.some(exam=>exam.id===state.analyticsExamId))state.analyticsExamId=exams[0].id;
  const exam=exams.find(item=>item.id===state.analyticsExamId), qids=questionIdsForExam(exam.id), attempts=state.data.attempts.filter(a=>qids.has(a.question_id)), students=state.data.students.filter(s=>s.active&&s.school===exam.school&&s.grade===exam.grade);
  const tabs=`<div class="analytics-tabs">${exams.map(item=>`<button class="button ${item.id===exam.id?'primary':'quiet'} small" data-analytics-exam="${item.id}">${escapeHtml(item.school)} · ${escapeHtml(item.grade)} · ${escapeHtml(item.title)}</button>`).join('')}</div>`;
  const table=students.map(student=>{const own=attempts.filter(a=>a.student_id===student.id), accuracy=own.length?Math.round(own.filter(a=>a.correct).length/own.length*100):0;return `<tr><td><strong>${escapeHtml(student.name)}</strong></td><td>${new Set(own.map(a=>a.question_id)).size} / ${qids.size}</td><td>${accuracy}%</td><td>${own.length}</td><td class="${repeatedWrong(own)?'repeat-count':''}">${repeatedWrong(own)}</td></tr>`;}).join('');
  const passageDetails=passagesForExam(exam.id).map(passage=>{const ids=new Set(questionsFor(passage.id).filter(q=>q.status==='available').map(q=>q.id)), own=attempts.filter(a=>ids.has(a.question_id)), wrong=[...new Set(own.filter(a=>!a.correct).map(a=>state.data.students.find(s=>s.id===a.student_id)?.name).filter(Boolean))];return `<div class="recent-row"><span>${escapeHtml(passage.title)}<br><small>accuracy ${own.length?Math.round(own.filter(a=>a.correct).length/own.length*100):0}% · ${own.length} attempts</small></span><strong>${wrong.length?'오답: '+wrong.map(escapeHtml).join(', '):'오답 없음'}</strong></div>`;}).join('');
  root.innerHTML=`${tabs}<div class="table-wrap"><table><thead><tr><th>학생</th><th>Completed</th><th>Accuracy</th><th>Total attempts</th><th>반복 오답</th></tr></thead><tbody>${table||'<tr><td colspan="5">이 학교·학년에 등록된 활성 학생이 없습니다.</td></tr>'}</tbody></table></div><div class="detail-grid"><section class="card detail-card"><h2>최근 attempts</h2>${attempts.slice(0,30).map(a=>{const student=state.data.students.find(s=>s.id===a.student_id),passage=passageFor(a.question_id);return `<div class="recent-row"><span>${escapeHtml(student?.name||'학생')} · ${escapeHtml(passage?.title||'Passage')}</span><strong>${a.correct?'정답':'오답'} · ${formatDate(a.created_at)} · ${Math.round(a.elapsed_ms/1000)}초</strong></div>`;}).join('')||'<p class="lead">아직 시도가 없습니다.</p>'}</section><section class="card detail-card"><h2>Passage 상세</h2>${passageDetails||'<p class="lead">Available 문제가 없습니다.</p>'}</section></div>`;
}

const impactLabels={sentences:'문장',questions:'문제',examLinks:'연결된 Exam',passageLinks:'포함 지문',attempts:'풀이 기록',savedWords:'저장 단어',savedSentences:'저장 문장',wordLookups:'단어 조회 기록',translationViews:'해석 조회 기록'};
async function openDelete(targetType,targetId){
  const impact=await safely(()=>call('delete_impact',{targetType,targetId},state.token,'삭제 가능 여부를 확인하는 중…'));if(!impact)return;state.deleteTarget={targetType,targetId,impact};
  const typeLabel={student:'학생',passage:'지문',exam:'Exam'}[targetType],counts=Object.entries(impact.counts).filter(([,count])=>count>0);
  $('#delete-title').textContent=`${typeLabel} 삭제`;
  $('#delete-content').innerHTML=`<p class="lead"><strong>${escapeHtml(impact.label)}</strong> 삭제 영향입니다.</p>${counts.length?`<ul class="impact-list">${counts.map(([kind,count])=>`<li><span>${escapeHtml(impactLabels[kind]||kind)}</span><strong>${count}건</strong></li>`).join('')}</ul>`:'<p class="lead">연결 데이터가 없습니다.</p>'}${impact.allowed?`<p class="lead">삭제하면 복구할 수 없습니다. DELETE를 입력하세요.</p><form id="delete-form"><label><span>확인 문구</span><input name="confirmation" autocomplete="off" placeholder="DELETE" required></label><button class="button danger" type="submit" disabled>${typeLabel} 삭제</button></form>`:`<div class="result bad">학습기록이 있어 삭제할 수 없습니다. 위 기록을 보존합니다.</div>`}`;
  $('#delete-modal').classList.add('on');$('#delete-modal').setAttribute('aria-hidden','false');
}
function closeDelete(){$('#delete-modal').classList.remove('on');$('#delete-modal').setAttribute('aria-hidden','true');state.deleteTarget=null;}
function closeImportPreview(){$('#passage-import-modal').classList.remove('on');$('#passage-import-modal').setAttribute('aria-hidden','true');state.importDraft=null;}
function updateImportValidation(){const errors=validatePassageRows(state.importDraft?.rows),status=$('#passage-import-validation'),save=$('[data-confirm-passage-import]');if(status)status.innerHTML=errors.length?`<div class="result bad">⚠ ${escapeHtml(errors[0])}</div>`:`<div class="result good">✓ ${state.importDraft.rows.length}개 행 정상</div>`;if(save)save.disabled=errors.length>0;return errors;}
function renderImportPreview(){const draft=state.importDraft;if(!draft)return;$('#passage-import-content').innerHTML=`<p class="lead compact">한 행은 그대로 한 Sentence가 됩니다. 영어 셀 내부는 다시 분리하지 않습니다.</p><div class="import-preview-grid" role="table" aria-label="지문 문장 미리보기"><div class="import-preview-head" role="row"><span>번호</span><span>ENGLISH</span><span>한국어</span></div>${draft.rows.map((row,index)=>`<div class="import-preview-row" role="row"><strong>${String(index+1).padStart(2,'0')}</strong><textarea rows="3" aria-label="${index+1}번 영어" data-import-index="${index}" data-import-field="text">${escapeHtml(row.text)}</textarea><textarea rows="3" aria-label="${index+1}번 한국어" data-import-index="${index}" data-import-field="translation">${escapeHtml(row.translation)}</textarea></div>`).join('')}</div><div id="passage-import-validation"></div><div class="editor-actions"><button class="button quiet" type="button" data-import-back>돌아가기</button><button class="button primary" type="button" data-confirm-passage-import>${draft.rows.length}개 문장 저장</button></div>`;updateImportValidation();$('#passage-import-modal').classList.add('on');$('#passage-import-modal').setAttribute('aria-hidden','false');}
function renderImportSuccess(data){state.importDraft={...state.importDraft,saved:data};const label=data.passage.source_label||data.passage.title,count=data.sentences.length;$('#passage-import-content').innerHTML=`<div class="import-success"><div class="result good">✓ ${escapeHtml(label)} 지문을 저장했습니다.</div><h3>${count}개 문장 · ${count}개 해석</h3><div class="editor-actions"><button class="button quiet" type="button" data-import-library>지문 목록으로</button><button class="button primary" type="button" data-admin-reader-preview>학생 화면에서 보기</button></div></div>`;}
function renderAdminReaderPreview(){const data=state.importDraft?.saved;if(!data)return;$('#passage-import-content').innerHTML=`<div class="reader-shell admin-reader-preview"><p class="eyebrow">ADMIN READER PREVIEW</p><h2>${escapeHtml(data.passage.title)}</h2><p class="lead compact">영어 문장을 눌러 저장된 같은 행의 한국어 해석을 확인하세요.</p><div class="study-sentences">${data.sentences.map((sentence,index)=>`<button class="study-sentence" type="button" data-admin-preview-sentence><span class="sentence-no">${String(index+1).padStart(2,'0')}</span><span><span class="preview-english">${escapeHtml(sentence.text)}</span><span class="preview-translation" hidden>${escapeHtml(sentence.translation)}</span></span></button>`).join('')}</div><div class="player-actions"><button class="button quiet" type="button" data-import-library>지문 목록으로</button></div></div>`;}
document.addEventListener('change',event=>{if(event.target.id==='student-school-filter'||event.target.id==='student-grade-filter')renderStudents();if(event.target.dataset.selectPassage){if(event.target.checked)state.selectedPassageIds.add(event.target.dataset.selectPassage);else state.selectedPassageIds.delete(event.target.dataset.selectPassage);renderPassageSelection();}});
document.addEventListener('change',event=>{if(['passage-grade-filter','passage-type-filter','passage-year-filter','passage-month-filter'].includes(event.target.id)){state.passagePage=0;renderPassages();}if(event.target.id==='passage-source-type'){const form=event.target.closest('form'),mock=event.target.value==='MOCK_EXAM';$$('[data-mock-meta]').forEach(item=>item.hidden=!mock);$$('[data-textbook-meta]').forEach(item=>item.hidden=mock);const title=form?.querySelector('[name="title"]');if(title){title.disabled=mock;title.required=!mock;}for(const field of form?.querySelectorAll('[name="sourceYear"],[name="sourceMonth"],[name="questionNumber"]')||[])field.required=mock;}});
document.addEventListener('input',event=>{if(event.target.closest('#delete-form'))event.target.closest('form').querySelector('button[type="submit"]').disabled=event.target.value!=='DELETE';if(event.target.matches('[data-import-field]')&&state.importDraft){state.importDraft.rows[Number(event.target.dataset.importIndex)][event.target.dataset.importField]=event.target.value;updateImportValidation();}});
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(event.target.closest('[data-close-import-preview]')||button?.hasAttribute('data-import-back'))return closeImportPreview();if(button?.hasAttribute('data-import-library')){closeImportPreview();route('passages');return;}if(button?.hasAttribute('data-admin-reader-preview'))return renderAdminReaderPreview();if(button?.hasAttribute('data-admin-preview-sentence')){const translation=button.querySelector('.preview-translation');translation.hidden=!translation.hidden;button.classList.toggle('translation-open',!translation.hidden);return;}if(button?.hasAttribute('data-confirm-passage-import')){const errors=updateImportValidation();if(errors.length)return;const draft=state.importDraft,data=await safely(()=>call('create_passage',{...draft.meta,sentenceRows:draft.rows.map(row=>({text:row.text.trim(),translation:row.translation.trim()}))},state.token,'지문과 해석을 저장하는 중…'));if(!data)return;const form=$('#create-passage-form');form.reset();const title=form.querySelector('[name="title"]');if(title){title.disabled=false;title.required=true;}$$('[data-mock-meta]').forEach(item=>item.hidden=true);$$('[data-textbook-meta]').forEach(item=>item.hidden=false);await loadAdmin();renderImportSuccess(data);}});
document.addEventListener('click',event=>{const button=event.target.closest('button');if(event.target.closest('[data-close-delete]'))return closeDelete();if(event.target.closest('[data-close-passage]'))return closePassage();if(button?.dataset.deleteStudent)return openDelete('student',button.dataset.deleteStudent);if(button?.dataset.deletePassage)return openDelete('passage',button.dataset.deletePassage);if(button?.dataset.deleteExam)return openDelete('exam',button.dataset.deleteExam);if(button?.hasAttribute('data-clear-passage-selection')){state.selectedPassageIds.clear();renderPassages();return;}if(button?.dataset.editPassage)return openPassage(button.dataset.editPassage);if(button?.dataset.passagePage){state.passagePage+=button.dataset.passagePage==='next'?1:-1;return renderPassages();}});
document.addEventListener('submit',async event=>{const form=event.target;if(form.id!=='delete-form')return;event.preventDefault();const target=state.deleteTarget;if(!target)return;const confirmation=new FormData(form).get('confirmation'),op={student:'delete_student',passage:'delete_passage',exam:'delete_exam'}[target.targetType],idKey={student:'studentId',passage:'passageId',exam:'examId'}[target.targetType];const data=await safely(()=>call(op,{[idKey]:target.targetId,confirmation},state.token,'안전하게 삭제하는 중…'));if(data){closeDelete();state.selectedPassageIds.delete(target.targetId);await loadAdmin();toast('삭제했습니다.');}});
document.addEventListener('click',async event=>{if(event.target.closest('[data-close-modal]'))return closeEditor();const button=event.target.closest('button');if(!button)return;if(button.dataset.route)return route(button.dataset.route);if(button.id==='theme-toggle')return applyTheme(document.body.classList.contains('dark')?'light':'dark');if(button.id==='admin-logout')return logout();if(['refresh-admin','refresh-passages','refresh-exams','refresh-analytics'].includes(button.id))return loadAdmin();if(button.dataset.previewQuestion)return openEditor(button.dataset.previewQuestion);if(button.dataset.questionStatus)return setStatus(button.dataset.questionStatus,button.dataset.status);if(button.dataset.deleteQuestion)return removeQuestion(button.dataset.deleteQuestion);if(button.dataset.editorMove){captureEditor();const index=state.editor.chunks.findIndex(c=>c.id===button.closest('[data-editor-chunk]').dataset.editorChunk),next=button.dataset.editorMove==='up'?index-1:index+1;if(next>=0&&next<state.editor.chunks.length)[state.editor.chunks[index],state.editor.chunks[next]]=[state.editor.chunks[next],state.editor.chunks[index]];return renderEditor();}if(button.hasAttribute('data-save-question'))return saveEditor();if(button.hasAttribute('data-regenerate-question'))return regenerate();if(button.hasAttribute('data-editor-approve')){const q=state.data.questions.find(item=>item.id===state.editor.questionId);return setStatus(q.id,q.status==='available'?'draft':'available');}if(button.hasAttribute('data-editor-delete'))return removeQuestion(state.editor.questionId);if(button.dataset.analyticsExam){state.analyticsExamId=button.dataset.analyticsExam;return renderAnalytics();}});
document.addEventListener('submit',async event=>{event.preventDefault();const form=event.target,formData=new FormData(form),values=Object.fromEntries(formData);if(form.id==='admin-login-form')return login(form);if(form.id==='create-student-form'){const data=await safely(()=>call('create_student',values));if(data){form.reset();await loadAdmin();}return;}if(form.id==='create-exam-from-passages'){const passageIds=[...state.selectedPassageIds];const data=await safely(()=>call('create_exam',{...values,passageIds},state.token,'시험범위를 만드는 중…'));if(data){state.selectedPassageIds.clear();await loadAdmin();route('exams');toast(`${passageIds.length}개 지문으로 Exam을 만들었습니다.`);}return;}if(form.id==='create-passage-form'){const parsed=parsePassageRows(values.tsv),error=$('#passage-import-error');if(parsed.errors.length){error.textContent=`⚠ ${parsed.errors[0]}`;return;}error.textContent='';const mock=values.sourceType==='MOCK_EXAM',number=String(values.questionNumber||'');if(mock&&!number)return toast('모의고사 문항 번호를 선택해 주세요.');delete values.tsv;values.title=mock?`${values.sourceYear}년 ${values.sourceMonth}월 ${number}번`:values.title;values.sourceLabel=mock?`${number}번`:'';state.importDraft={meta:values,rows:parsed.rows.map(({text,translation})=>({text,translation}))};renderImportPreview();return;}if(form.id==='update-passage-form'){const data=await safely(()=>call('update_passage',{...values,passageId:state.passageEditorId},state.token,'지문을 저장하는 중…'));if(data){closePassage();await loadAdmin();toast('지문 정보를 저장했습니다.');}return;}if(form.dataset.generatePassage){const data=await safely(()=>call('generate_order',{passageId:form.dataset.generatePassage,difficulty:Number(values.difficulty)},state.token,'AI가 의미 흐름을 분석하는 중…'));if(data){closePassage();await loadAdmin();openEditor(data.question.id);}return;}if(form.dataset.updateExam){const passageIds=[...new FormData(form).getAll('passageIds')];const data=await safely(()=>call('update_exam_passages',{examId:form.dataset.updateExam,passageIds},state.token,'시험범위를 저장하는 중…'));if(data){await loadAdmin();toast('시험범위를 저장했습니다.');}return;}if(form.dataset.resetPin){const data=await safely(()=>call('set_student_pin',{studentId:form.dataset.resetPin,pin:values.pin}));if(data){form.reset();toast('PIN을 변경하고 기존 학생 세션을 종료했습니다.');}return;}});
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if($('#question-modal').classList.contains('on'))closeEditor();if($('#passage-modal').classList.contains('on'))closePassage();if($('#delete-modal').classList.contains('on'))closeDelete();if($('#passage-import-modal').classList.contains('on'))closeImportPreview();});
applyTheme(localStorage.getItem('ready-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));try{const previous=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');if(previous?.token){state.token=previous.token;loadAdmin();}else showLogin();}catch{showLogin();}
