import { readyApi } from '../api.js';

const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const SESSION_KEY = 'ready-admin-session';
const state = { token:'', data:null, route:'students', editor:null, passageEditorId:null, analyticsExamId:null, studentDeleteId:null, passagePage:0 };
let busyCount = 0, toastTimer;
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
const formatDate = value => value ? new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)) : '—';
function setBusy(on, label='잠시만요…') { busyCount=Math.max(0,busyCount+(on?1:-1)); $('#busy').hidden=!busyCount; $('#busy span:last-child').textContent=label; }
function toast(message) { $('#toast').textContent=message; $('#toast').classList.add('on'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').classList.remove('on'),3200); }
function applyTheme(theme) { const dark=theme==='dark'; document.documentElement.classList.toggle('dark',dark); document.body.classList.toggle('dark',dark); localStorage.setItem('ready-theme',theme); }
function clearSession() { sessionStorage.removeItem(SESSION_KEY); state.token=''; state.data=null; }
async function call(op,data={},token=state.token,label='잠시만요…') { setBusy(true,label); try{return await readyApi(op,data,token);}finally{setBusy(false);} }
async function safely(job,{auth=true}={}) { try{return await job();}catch(error){if(auth&&error.status===401){clearSession();showLogin();}toast(error.message||'요청을 처리하지 못했습니다.');return null;} }
function showLogin() { $('#admin-login').hidden=false; $('#admin-nav').hidden=true; $('#admin-logout').hidden=true; $$('.view').forEach(view=>view.classList.remove('on')); }
function route(name) { state.route=name; $$('.view').forEach(view=>view.classList.toggle('on',view.id===`v-${name}`)); $$('.navbtn').forEach(button=>button.classList.toggle('on',button.dataset.route===name)); if(name==='analytics')renderAnalytics(); }
async function login(form) { const password=new FormData(form).get('password'); const data=await safely(()=>call('admin_login',{password},'','관리자 비밀번호를 확인하는 중…'),{auth:false}); form.reset(); if(!data)return; state.token=data.session.token; sessionStorage.setItem(SESSION_KEY,JSON.stringify(data.session)); await loadAdmin(); }
async function loadAdmin() { const data=await safely(()=>call('teacher_bootstrap',{},state.token,'관리자 화면을 불러오는 중…')); if(!data)return; state.data=data; $('#admin-login').hidden=true; $('#admin-nav').hidden=false; $('#admin-logout').hidden=false; renderStudents(); renderPassages(); renderExams(); route(state.route); }
async function logout() { if(state.token)await safely(()=>call('logout')); clearSession(); showLogin(); }
function questionsFor(passageId){return state.data.questions.filter(question=>question.passage_id===passageId);}
function passagesForExam(examId){const byId=new Map(state.data.passages.map(passage=>[passage.id,passage]));return state.data.examPassages.filter(link=>link.exam_id===examId).sort((a,b)=>a.position-b.position).map(link=>byId.get(link.passage_id)).filter(Boolean);}
function passageFor(questionId){const q=state.data.questions.find(item=>item.id===questionId);return state.data.passages.find(item=>item.id===q?.passage_id);}

function renderStudents() {
  const school=$('#student-school-filter')?.value||'',grade=$('#student-grade-filter')?.value||'';
  const students=state.data.students.filter(student=>(!school||student.school===school)&&(!grade||student.grade===grade));
  const root=$('#admin-students');
  root.innerHTML=students.length?`<div class="table-wrap student-table"><table><thead><tr><th>이름</th><th>학교 / 학년</th><th>PIN 변경</th><th></th></tr></thead><tbody>${students.map(student=>`<tr><td><strong>${escapeHtml(student.name)}</strong></td><td>${escapeHtml(student.school)} · ${escapeHtml(student.grade)}</td><td><form class="pin-reset" data-reset-pin="${student.id}"><input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4,6}" minlength="4" maxlength="6" autocomplete="new-password" placeholder="새 PIN" required><button class="button quiet small" type="submit">변경</button></form></td><td><button class="button danger small" type="button" data-delete-student="${student.id}">삭제</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">조건에 맞는 학생이 없습니다.</div>';
}
function renderPassages(){const root=$('#passage-library');if(!root)return;const grade=$('#passage-grade-filter')?.value||'',type=$('#passage-type-filter')?.value||'',year=$('#passage-year-filter')?.value||'',month=$('#passage-month-filter')?.value||'';const rows=state.data.passages.filter(p=>(!grade||p.grade===grade)&&(!type||p.source_type===type)&&(!year||String(p.source_year)===year)&&(!month||String(p.source_month)===month));const pageSize=15,totalPages=Math.max(1,Math.ceil(rows.length/pageSize));state.passagePage=Math.min(state.passagePage,totalPages-1);const page=rows.slice(state.passagePage*pageSize,(state.passagePage+1)*pageSize);root.innerHTML=`<p class="library-note">행을 끌어 지문 라이브러리의 기본 순서를 바꿀 수 있습니다.</p><div class="table-wrap"><table><thead><tr><th></th><th>제목</th><th>종류</th><th>학년</th><th>출처</th><th>문제</th><th></th></tr></thead><tbody>${page.map(p=>`<tr draggable="true" data-passage-row="${p.id}"><td class="drag-cell" aria-label="순서 변경">⋮⋮</td><td><button class="text-button" data-edit-passage="${p.id}">${escapeHtml(p.title)}</button></td><td>${p.source_type==='MOCK_EXAM'?'모의고사':'교과서'}</td><td>${escapeHtml(p.grade)}</td><td>${escapeHtml([p.source_year,p.source_month&&p.source_month+'월',p.source_label].filter(Boolean).join(' · ')||'—')}</td><td>${questionsFor(p.id).length}</td><td><button class="button quiet small" data-edit-passage="${p.id}">수정</button><button class="button danger small" data-delete-passage="${p.id}">삭제</button></td></tr>`).join('')||'<tr><td colspan="7">조건에 맞는 지문이 없습니다.</td></tr>'}</tbody></table></div><div class="pagination"><button class="button quiet small" data-passage-page="prev" ${state.passagePage===0?'disabled':''}>← Prev</button><span>${state.passagePage+1} / ${totalPages}</span><button class="button quiet small" data-passage-page="next" ${state.passagePage===totalPages-1?'disabled':''}>Next →</button></div>`;}
function openPassage(passageId){const passage=state.data.passages.find(item=>item.id===passageId);if(!passage)return;state.passageEditorId=passageId;const hasQuestions=questionsFor(passageId).length>0;$('#passage-editor').innerHTML=`<form id="update-passage-form"><div class="form-grid"><label><span>제목</span><input name="title" value="${escapeHtml(passage.title)}" required></label><label><span>종류</span><select name="sourceType"><option value="TEXTBOOK" ${passage.source_type==='TEXTBOOK'?'selected':''}>교과서</option><option value="MOCK_EXAM" ${passage.source_type==='MOCK_EXAM'?'selected':''}>모의고사</option></select></label><label><span>학년</span><select name="grade">${['1학년','2학년','3학년'].map(value=>`<option ${passage.grade===value?'selected':''}>${value}</option>`).join('')}</select></label><label><span>연도</span><input name="sourceYear" value="${passage.source_year||''}"></label><label><span>월</span><input name="sourceMonth" value="${passage.source_month||''}"></label><label><span>출처</span><input name="sourceLabel" value="${escapeHtml(passage.source_label||'')}"></label><label><span>영어 원문 ${hasQuestions?'(문제가 있어 수정 불가)':''}</span><textarea name="sourceText" ${hasQuestions?'disabled':''}>${escapeHtml(passage.source_text)}</textarea></label></div><button class="button primary" type="submit">지문 저장</button></form><form class="actions" data-generate-passage="${passage.id}" style="margin-top:16px"><select name="difficulty">${[1,2,3,4].map(level=>`<option value="${level}">ORDER Level ${level}</option>`).join('')}</select><button class="button quiet" type="submit">AI 문제 생성</button></form><div class="passage-list">${questionsFor(passage.id).map(question=>`<div class="question-row"><strong>ORDER · Level ${question.difficulty}</strong><button class="button quiet small" type="button" data-preview-question="${question.id}">Preview</button></div>`).join('')}</div>`;$('#passage-modal').classList.add('on');$('#passage-modal').setAttribute('aria-hidden','false');}
function closePassage(){$('#passage-modal').classList.remove('on');$('#passage-modal').setAttribute('aria-hidden','true');state.passageEditorId=null;}
function renderExams() {
  const root=$('#teacher-exams');
  root.innerHTML=`<div class="exam-list">${state.data.exams.map(exam=>{const passages=passagesForExam(exam.id),included=new Set(passages.map(p=>p.id)),count=passages.reduce((sum,p)=>sum+questionsFor(p.id).length,0);return `<section class="card teacher-set"><div class="card-head"><div><p class="eyebrow">${escapeHtml(exam.school)} · ${escapeHtml(exam.grade)}</p><h2>${escapeHtml(exam.title)}</h2><p class="lead compact">지문 ${passages.length}개 · 문제 ${count}개</p></div><button class="button danger small" type="button" data-delete-exam="${exam.id}">Exam 삭제</button></div><div class="passage-list">${passages.map((p,index)=>`<div class="recent-row"><span>${index+1}. ${escapeHtml(p.title)}</span><strong>${questionsFor(p.id).length}문제</strong></div>`).join('')||'<div class="empty">포함된 지문이 없습니다.</div>'}</div><details class="exam-range"><summary>시험범위 지문 수정</summary><form data-update-exam="${exam.id}" class="exam-passage-picker"><p class="lead compact">체크한 지문만 이 Exam에 포함됩니다. 지문 라이브러리의 기본 순서가 시험 안의 순서로 저장됩니다.</p>${state.data.passages.map(p=>`<label class="check-row"><input type="checkbox" name="passageIds" value="${p.id}" ${included.has(p.id)?'checked':''}><span>${escapeHtml(p.grade)} · ${escapeHtml(p.title)} <small>${questionsFor(p.id).length}문제</small></span></label>`).join('')}<button class="button primary small" type="submit">시험범위 저장</button></form></details></section>`;}).join('')||'<div class="empty">아직 Exam이 없습니다.</div>'}</div>`;
}
function renderPassage(passage) {
  const sentences=state.data.sentences.filter(sentence=>sentence.passage_id===passage.id), questions=questionsFor(passage.id);
  return `<article class="passage"><div class="passage-head"><div><h3>${escapeHtml(passage.title)}</h3><p>${sentences.length} sentences · 원문 ID 고정</p></div><form class="actions" data-generate-passage="${passage.id}"><select name="difficulty">${[1,2,3,4].map(level=>`<option value="${level}">Level ${level}</option>`).join('')}</select><button class="button quiet small" type="submit">문제 추가</button></form></div>${questions.map(question=>`<div class="question-row"><div><span class="pill ${question.status==='available'?'good':'warn'}">${question.status}</span> <strong>ORDER · Level ${question.difficulty}</strong><div class="meta">${question.payload.chunks.length} chunks · generation ${question.generation}</div></div><div class="actions"><button class="button quiet small" type="button" data-preview-question="${question.id}">Preview</button>${question.status==='draft'?`<button class="button primary small" type="button" data-question-status="${question.id}" data-status="available">Available 승인</button>`:`<button class="button quiet small" type="button" data-question-status="${question.id}" data-status="draft">Draft로 전환</button>`}<button class="button danger small" type="button" data-delete-question="${question.id}">삭제</button></div></div>`).join('')}</article>`;
}

function openEditor(questionId) { const question=state.data.questions.find(item=>item.id===questionId); if(!question)return; const order=question.payload.correctOrder.map(id=>question.payload.chunks.find(chunk=>chunk.id===id)).filter(Boolean); state.editor={questionId,passageId:question.passage_id,difficulty:question.difficulty,chunks:structuredClone(order)}; renderEditor(); $('#question-modal').classList.add('on'); $('#question-modal').setAttribute('aria-hidden','false'); }
function closeEditor() { $('#question-modal').classList.remove('on'); $('#question-modal').setAttribute('aria-hidden','true'); state.editor=null; }
function renderEditor() { const editor=state.editor, question=state.data.questions.find(item=>item.id===editor.questionId); $('#question-editor').innerHTML=`<div class="editor-note">정답 순서와 문구를 검수합니다. Available 승인 순간, 해당 학교·학년 학생에게 보입니다.</div><div class="chunk-list">${editor.chunks.map((chunk,index)=>`<div class="chunk-edit" data-editor-chunk="${escapeHtml(chunk.id)}"><div class="chunk-number">${index+1}</div><textarea>${escapeHtml(chunk.text)}</textarea><div class="move-stack"><button type="button" data-editor-move="up" ${index===0?'disabled':''}>↑</button><button type="button" data-editor-move="down" ${index===editor.chunks.length-1?'disabled':''}>↓</button></div></div>`).join('')}</div><div class="editor-actions"><button class="button primary" type="button" data-save-question>수정 저장</button><button class="button quiet" type="button" data-regenerate-question>AI 다시 생성</button><button class="button ${question.status==='available'?'quiet':'primary'}" type="button" data-editor-approve>${question.status==='available'?'Draft로 전환':'Available 승인'}</button><button class="button danger" type="button" data-editor-delete>삭제</button></div>`; }
function captureEditor() { if(!state.editor)return; $$('[data-editor-chunk]').forEach(row=>{const chunk=state.editor.chunks.find(item=>item.id===row.dataset.editorChunk);if(chunk)chunk.text=row.querySelector('textarea').value.trim();}); }
async function saveEditor(){captureEditor();const payload={difficulty:state.editor.difficulty,chunks:state.editor.chunks,correctOrder:state.editor.chunks.map(chunk=>chunk.id)};const data=await safely(()=>call('update_question',{questionId:state.editor.questionId,payload},state.token,'문제를 저장하는 중…'));if(data){toast('수정 내용을 저장했습니다.');closeEditor();await loadAdmin();}}
async function setStatus(questionId,status){const data=await safely(()=>call('set_question_status',{questionId,status}));if(data){toast(status==='available'?'학생에게 문제를 열었습니다.':'문제를 Draft로 전환했습니다.');closeEditor();await loadAdmin();}}
async function removeQuestion(questionId){if(!confirm('이 문제를 삭제할까요?'))return;const data=await safely(()=>call('delete_question',{questionId}));if(data){closeEditor();await loadAdmin();}}
async function regenerate(){const editor=state.editor,data=await safely(()=>call('generate_order',{passageId:editor.passageId,difficulty:editor.difficulty,replaceQuestionId:editor.questionId},state.token,'AI가 의미 흐름을 분석하는 중…'));if(data){closeEditor();await loadAdmin();openEditor(data.question.id);}}

function questionIdsForExam(examId){return new Set(passagesForExam(examId).flatMap(p=>questionsFor(p.id).filter(q=>q.status==='available').map(q=>q.id)));}
function repeatedWrong(attempts){const count=new Map();attempts.filter(a=>!a.correct).forEach(a=>count.set(a.question_id,(count.get(a.question_id)||0)+1));return [...count.values()].filter(n=>n>=2).length;}
function renderAnalytics(){
  const root=$('#analytics-content'), exams=state.data.exams;if(!exams.length){root.innerHTML='<div class="empty">Exam을 만든 뒤 학습 기록을 확인할 수 있습니다.</div>';return;}if(!state.analyticsExamId||!exams.some(exam=>exam.id===state.analyticsExamId))state.analyticsExamId=exams[0].id;
  const exam=exams.find(item=>item.id===state.analyticsExamId), qids=questionIdsForExam(exam.id), attempts=state.data.attempts.filter(a=>qids.has(a.question_id)), students=state.data.students.filter(s=>s.active&&s.school===exam.school&&s.grade===exam.grade);
  const tabs=`<div class="analytics-tabs">${exams.map(item=>`<button class="button ${item.id===exam.id?'primary':'quiet'} small" data-analytics-exam="${item.id}">${escapeHtml(item.school)} · ${escapeHtml(item.grade)} · ${escapeHtml(item.title)}</button>`).join('')}</div>`;
  const table=students.map(student=>{const own=attempts.filter(a=>a.student_id===student.id), accuracy=own.length?Math.round(own.filter(a=>a.correct).length/own.length*100):0;return `<tr><td><strong>${escapeHtml(student.name)}</strong></td><td>${new Set(own.map(a=>a.question_id)).size} / ${qids.size}</td><td>${accuracy}%</td><td>${own.length}</td><td class="${repeatedWrong(own)?'repeat-count':''}">${repeatedWrong(own)}</td></tr>`;}).join('');
  const passageDetails=passagesForExam(exam.id).map(passage=>{const ids=new Set(questionsFor(passage.id).filter(q=>q.status==='available').map(q=>q.id)), own=attempts.filter(a=>ids.has(a.question_id)), wrong=[...new Set(own.filter(a=>!a.correct).map(a=>state.data.students.find(s=>s.id===a.student_id)?.name).filter(Boolean))];return `<div class="recent-row"><span>${escapeHtml(passage.title)}<br><small>accuracy ${own.length?Math.round(own.filter(a=>a.correct).length/own.length*100):0}% · ${own.length} attempts</small></span><strong>${wrong.length?'오답: '+wrong.map(escapeHtml).join(', '):'오답 없음'}</strong></div>`;}).join('');
  root.innerHTML=`${tabs}<div class="table-wrap"><table><thead><tr><th>학생</th><th>Completed</th><th>Accuracy</th><th>Total attempts</th><th>반복 오답</th></tr></thead><tbody>${table||'<tr><td colspan="5">이 학교·학년에 등록된 활성 학생이 없습니다.</td></tr>'}</tbody></table></div><div class="detail-grid"><section class="card detail-card"><h2>최근 attempts</h2>${attempts.slice(0,30).map(a=>{const student=state.data.students.find(s=>s.id===a.student_id),passage=passageFor(a.question_id);return `<div class="recent-row"><span>${escapeHtml(student?.name||'학생')} · ${escapeHtml(passage?.title||'Passage')}</span><strong>${a.correct?'정답':'오답'} · ${formatDate(a.created_at)} · ${Math.round(a.elapsed_ms/1000)}초</strong></div>`;}).join('')||'<p class="lead">아직 시도가 없습니다.</p>'}</section><section class="card detail-card"><h2>Passage 상세</h2>${passageDetails||'<p class="lead">Available 문제가 없습니다.</p>'}</section></div>`;
}

function openStudentDelete(studentId){const student=state.data.students.find(item=>item.id===studentId);if(!student)return;state.studentDeleteId=studentId;const attempts=state.data.attempts.filter(item=>item.student_id===studentId).length;$('#student-delete-content').innerHTML=`<p class="lead"><strong>${escapeHtml(student.name)}</strong> 학생을 삭제할까요?</p>${attempts?`<div class="result bad">이 학생에게 학습기록 ${attempts}건이 있어 삭제할 수 없습니다. 학습기록은 보존됩니다.</div>`:`<p class="lead">학습기록이 없습니다. 삭제하려면 DELETE를 입력하세요.</p><form id="student-delete-form"><label><span>확인 문구</span><input name="confirmation" autocomplete="off" placeholder="DELETE" required></label><button class="button danger" type="submit" disabled>학생 삭제</button></form>`}`;$('#student-delete-modal').classList.add('on');$('#student-delete-modal').setAttribute('aria-hidden','false');}
function closeStudentDelete(){$('#student-delete-modal').classList.remove('on');$('#student-delete-modal').setAttribute('aria-hidden','true');state.studentDeleteId=null;}
document.addEventListener('change',event=>{if(event.target.id==='student-school-filter'||event.target.id==='student-grade-filter')renderStudents();});
document.addEventListener('change',event=>{if(['passage-grade-filter','passage-type-filter','passage-year-filter','passage-month-filter'].includes(event.target.id)){state.passagePage=0;renderPassages();}if(event.target.id==='passage-source-type'){const form=event.target.closest('form'),mock=event.target.value==='MOCK_EXAM';$$('[data-mock-meta]').forEach(item=>item.hidden=!mock);$$('[data-textbook-meta]').forEach(item=>item.hidden=mock);const title=form?.querySelector('[name="title"]');if(title){title.disabled=mock;title.required=!mock;}for(const field of form?.querySelectorAll('[name="sourceYear"],[name="sourceMonth"],[name="questionNumber"]')||[])field.required=mock;}});
document.addEventListener('input',event=>{if(event.target.closest('#student-delete-form'))event.target.closest('form').querySelector('button[type="submit"]').disabled=event.target.value!=='DELETE';});
document.addEventListener('click',event=>{const button=event.target.closest('button');if(event.target.closest('[data-close-student-delete]'))return closeStudentDelete();if(event.target.closest('[data-close-passage]'))return closePassage();if(button?.dataset.deleteStudent)return openStudentDelete(button.dataset.deleteStudent);if(button?.dataset.editPassage)return openPassage(button.dataset.editPassage);if(button?.dataset.passagePage){state.passagePage+=button.dataset.passagePage==='next'?1:-1;return renderPassages();}if(button?.dataset.deleteExam){const confirmation=prompt('이 Exam에 학습기록이 있으면 삭제할 수 없습니다. 삭제하려면 DELETE를 입력하세요.');if(confirmation!=='DELETE')return;return safely(async()=>{const data=await call('delete_exam',{examId:button.dataset.deleteExam,confirmation});if(data){await loadAdmin();toast('Exam을 삭제했습니다.');}});}if(button?.dataset.deletePassage){if(!confirm('이 지문을 삭제할까요? 문제와 문장이 함께 삭제될 수 있습니다.'))return;return safely(async()=>{const data=await call('delete_passage',{passageId:button.dataset.deletePassage});if(data){await loadAdmin();}});}});
document.addEventListener('submit',async event=>{const form=event.target;if(form.id!=='student-delete-form')return;event.preventDefault();const data=await safely(()=>call('delete_student',{studentId:state.studentDeleteId,confirmation:new FormData(form).get('confirmation')},state.token,'학생을 삭제하는 중…'));if(data){closeStudentDelete();await loadAdmin();toast('학생을 삭제했습니다.');}});
document.addEventListener('click',async event=>{if(event.target.closest('[data-close-modal]'))return closeEditor();const button=event.target.closest('button');if(!button)return;if(button.dataset.route)return route(button.dataset.route);if(button.id==='theme-toggle')return applyTheme(document.body.classList.contains('dark')?'light':'dark');if(button.id==='admin-logout')return logout();if(button.id==='refresh-admin'||button.id==='refresh-exams'||button.id==='refresh-analytics')return loadAdmin();if(button.dataset.studentActive){const data=await safely(()=>call('set_student_active',{studentId:button.dataset.studentActive,active:button.dataset.active==='true'}));if(data)await loadAdmin();return;}if(button.dataset.previewQuestion)return openEditor(button.dataset.previewQuestion);if(button.dataset.questionStatus)return setStatus(button.dataset.questionStatus,button.dataset.status);if(button.dataset.deleteQuestion)return removeQuestion(button.dataset.deleteQuestion);if(button.dataset.editorMove){captureEditor();const index=state.editor.chunks.findIndex(c=>c.id===button.closest('[data-editor-chunk]').dataset.editorChunk),next=button.dataset.editorMove==='up'?index-1:index+1;if(next>=0&&next<state.editor.chunks.length)[state.editor.chunks[index],state.editor.chunks[next]]=[state.editor.chunks[next],state.editor.chunks[index]];return renderEditor();}if(button.hasAttribute('data-save-question'))return saveEditor();if(button.hasAttribute('data-regenerate-question'))return regenerate();if(button.hasAttribute('data-editor-approve')){const q=state.data.questions.find(item=>item.id===state.editor.questionId);return setStatus(q.id,q.status==='available'?'draft':'available');}if(button.hasAttribute('data-editor-delete'))return removeQuestion(state.editor.questionId);if(button.dataset.analyticsExam){state.analyticsExamId=button.dataset.analyticsExam;return renderAnalytics();}});
document.addEventListener('submit',async event=>{event.preventDefault();const form=event.target,formData=new FormData(form),values=Object.fromEntries(formData);if(form.id==='admin-login-form')return login(form);if(form.id==='create-student-form'){const data=await safely(()=>call('create_student',values));if(data){form.reset();await loadAdmin();}return;}if(form.id==='create-passage-form'){const rows=String(values.tsv||'').split(/\r?\n/).map(row=>row.split('\t').map(cell=>cell.trim())).filter(row=>row[0]||row[1]);if(!rows.length||rows.some(row=>row.length<2||!row[0]||!row[1]))return toast('영어 문장과 한국어 해석 두 열을 모든 행에 붙여넣어 주세요.');const mock=values.sourceType==='MOCK_EXAM',number=String(values.questionNumber||'');if(mock&&!number)return toast('모의고사 문항 번호를 선택해 주세요.');values.title=mock?`${values.sourceYear}년 ${values.sourceMonth}월 ${number}번`:values.title;values.sourceLabel=mock?`${number}번`:'';values.sourceText=rows.map(row=>row[0]).join(' ');values.sentenceRows=rows.map(row=>({text:row[0],translation:row[1]}));delete values.tsv;const data=await safely(()=>call('create_passage',values,state.token,'표의 문장과 해석을 저장하는 중…'));if(data){form.reset();const title=form.querySelector('[name="title"]');if(title){title.disabled=false;title.required=true;}$$('[data-mock-meta]').forEach(item=>item.hidden=true);$$('[data-textbook-meta]').forEach(item=>item.hidden=false);await loadAdmin();toast('지문을 저장했습니다.');}return;}if(form.id==='update-passage-form'){const data=await safely(()=>call('update_passage',{...values,passageId:state.passageEditorId},state.token,'지문을 저장하는 중…'));if(data){closePassage();await loadAdmin();toast('지문 정보를 저장했습니다.');}return;}if(form.dataset.generatePassage){const data=await safely(()=>call('generate_order',{passageId:form.dataset.generatePassage,difficulty:Number(values.difficulty)},state.token,'AI가 의미 흐름을 분석하는 중…'));if(data){closePassage();await loadAdmin();openEditor(data.question.id);}return;}if(form.dataset.updateExam){const passageIds=[...new FormData(form).getAll('passageIds')];const data=await safely(()=>call('update_exam_passages',{examId:form.dataset.updateExam,passageIds},state.token,'시험범위를 저장하는 중…'));if(data){await loadAdmin();toast('시험범위를 저장했습니다.');}return;}if(form.dataset.resetPin){const data=await safely(()=>call('set_student_pin',{studentId:form.dataset.resetPin,pin:values.pin}));if(data){form.reset();toast('PIN을 변경하고 기존 학생 세션을 종료했습니다.');}return;}});
let draggedPassageId='';
document.addEventListener('dragstart',event=>{const row=event.target.closest('[data-passage-row]');if(!row)return;draggedPassageId=row.dataset.passageRow;row.classList.add('dragging');event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',draggedPassageId);});
document.addEventListener('dragend',event=>event.target.closest('[data-passage-row]')?.classList.remove('dragging'));
document.addEventListener('dragover',event=>{if(event.target.closest('[data-passage-row]')&&draggedPassageId){event.preventDefault();event.dataTransfer.dropEffect='move';}});
document.addEventListener('drop',event=>{const target=event.target.closest('[data-passage-row]');if(!target||!draggedPassageId||target.dataset.passageRow===draggedPassageId)return;event.preventDefault();const from=state.data.passages.findIndex(p=>p.id===draggedPassageId),to=state.data.passages.findIndex(p=>p.id===target.dataset.passageRow);if(from<0||to<0)return;const [moved]=state.data.passages.splice(from,1);state.data.passages.splice(to,0,moved);renderPassages();safely(async()=>{const data=await call('reorder_passages',{passageIds:state.data.passages.map(p=>p.id)},state.token,'지문 순서를 저장하는 중…');if(data)toast('지문 순서를 저장했습니다.');});draggedPassageId='';});
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if($('#question-modal').classList.contains('on'))closeEditor();if($('#passage-modal').classList.contains('on'))closePassage();if($('#student-delete-modal').classList.contains('on'))closeStudentDelete();});
applyTheme(localStorage.getItem('ready-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));try{const previous=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');if(previous?.token){state.token=previous.token;loadAdmin();}else showLogin();}catch{showLogin();}
