import { readyApi } from './api.js';

const $=s=>document.querySelector(s),esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const SESSION_KEY='ready-student-session',CACHE_INDEX='ready-passage-cache-v1:';
const state={token:'',student:null,selectedStudent:null,scope:null,passages:[],passage:null,sentences:[],tokens:[],sentenceBakes:[],occurrences:[],savedConceptIds:new Set(),savedSentenceIds:new Set(),library:null,activeOccurrenceId:null};
let busyCount=0,toastTimer,wordTimer,holdTimer,holdStart;
function busy(on,label='잠시만요…'){busyCount=Math.max(0,busyCount+(on?1:-1));$('#busy').hidden=!busyCount;$('#busy span:last-child').textContent=label;}
function toast(message,ms=1900){const node=$('#toast');node.textContent=message;node.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('on'),ms);}
function theme(next){const dark=next==='dark';document.documentElement.classList.toggle('dark',dark);document.body.classList.toggle('dark',dark);localStorage.setItem('ready-theme',next);}
async function call(op,data={},token=state.token,label='잠시만요…'){busy(true,label);try{return await readyApi(op,data,token);}finally{busy(false);}}
function record(op,data={}){readyApi(op,data,state.token).catch(()=>{});}
function clearSession(){localStorage.removeItem(SESSION_KEY);Object.assign(state,{token:'',student:null,scope:null,passages:[],library:null});}
async function safely(job,{auth=true}={}){try{return await job();}catch(error){if(auth&&error.status===401){clearSession();await chooseStudent();}toast(error.message||'요청을 처리하지 못했습니다.',3600);return null;}}
function show(...ids){['student-home','pin-login','student-sets','student-reader','student-library'].forEach(id=>$('#'+id).hidden=!ids.includes(id));}
function updateStudentNav(){const nav=$('#student-nav');nav.hidden=!state.token;$('#session-name').textContent='';$('#logout').hidden=!state.token;}

async function chooseStudent(){const data=await safely(()=>call('list_students',{},'','학생 목록을 불러오는 중…'),{auth:false});if(!data)return;state.selectedStudent=null;show('student-home');updateStudentNav();$('#student-list').innerHTML=data.students.length?data.students.map(s=>`<button class="student-button" type="button" data-student-id="${s.id}" data-student-name="${esc(s.name)}">${esc(s.name)}</button>`).join(''):'<div class="empty">등록된 학생이 없습니다.</div>';}
function openPin(student){state.selectedStudent=student;show('pin-login');$('#pin-student-name').textContent=student.name;$('#student-pin').focus();}
async function login(form){const values=Object.fromEntries(new FormData(form)),data=await safely(()=>call('student_login',{studentId:state.selectedStudent.id,pin:values.pin,remember:values.remember==='on'},'','PIN을 확인하는 중…'),{auth:false});form.reset();if(!data)return;state.token=data.session.token;state.student=data.student;if(data.session.remember)localStorage.setItem(SESSION_KEY,JSON.stringify(data.session));else localStorage.removeItem(SESSION_KEY);await loadDashboard();}
async function loadDashboard(){const data=await safely(()=>call('student_bootstrap',{},state.token,'학습 범위를 준비하는 중…'));if(!data)return;state.student=data.student;state.scope=data.scope;state.passages=data.passages;updateStudentNav();renderScope();}
function courseKey(passage){if(passage.source_type!=='TEXTBOOK')return '';const label=String(passage.source_label||'').trim();return label.replace(/\s*·\s*Part\s+\d+\s*$/i,'')||String(passage.title||'').split(' · ')[0];}
function passageChoice(passage,index){return `<button class="passage-row" type="button" data-start-passage="${passage.id}"><span><strong>${esc(passage.title)}</strong><small>${passage.source_type==='TEXTBOOK'?'교과서':'모의고사'} · 지문 ${index+1}</small></span><b aria-hidden="true">›</b></button>`;}
function scopePassagesHtml(){const groups=[];state.passages.forEach((passage,index)=>{const course=courseKey(passage),previous=groups.at(-1);if(course&&previous?.course===course)previous.items.push({passage,index});else groups.push({course,items:[{passage,index}]});});return groups.map(group=>group.course?`<section class="textbook-course"><details open><summary><span><small>TEXTBOOK</small><strong>${esc(group.course)}</strong></span><em>${group.items.length}개 지문</em></summary><div class="passage-list">${group.items.map(({passage,index})=>passageChoice(passage,index)).join('')}</div></details></section>`:`<div class="passage-list">${group.items.map(({passage,index})=>passageChoice(passage,index)).join('')}</div>`).join('');}
function continuation(){const key=`ready-last-passage:${state.student?.id}:${state.scope?.id}`,last=localStorage.getItem(key);return state.passages.find(p=>p.id===last)||state.passages[0];}
function renderScope(){show('student-sets');const next=continuation(),content=!state.scope?'<div class="empty scope-empty"><strong>아직 배정된 시험범위가 없습니다.</strong></div>':state.passages.length?scopePassagesHtml():'<div class="empty scope-empty"><strong>아직 배정된 지문이 없습니다.</strong></div>';$('#student-sets').innerHTML=`<div class="home-head"><span>Home</span><small>${state.scope?`${esc(state.student.school)} · ${esc(state.student.grade)}`:''}</small></div>${next?`<button class="start-study" type="button" data-start-passage="${next.id}"><span><strong>바로 시작</strong><small>${localStorage.getItem(`ready-last-passage:${state.student?.id}:${state.scope?.id}`)?'마지막으로 읽던 지문을 이어서 봅니다.':'첫 번째 지문부터 시작합니다.'}</small></span><b aria-hidden="true">→</b></button>`:''}<div class="home-tabs" role="tablist"><button type="button" class="active">지문별</button><button type="button" disabled aria-label="문제 유형 학습은 준비 중입니다">유형별</button><button type="button" disabled aria-label="오답복습은 준비 중입니다">오답복습</button></div><div class="home-content">${content}</div>`;}

const conceptOf=occurrence=>Array.isArray(occurrence?.concept)?occurrence.concept[0]:occurrence?.concept;
function tokenOccurrence(tokenId){return state.occurrences.filter(o=>(o.token_ids||[]).includes(tokenId)).sort((a,b)=>{const pa=conceptOf(a)?.kind==='phrase'?1:0,pb=conceptOf(b)?.kind==='phrase'?1:0;return pb-pa||(b.specificity||0)-(a.specificity||0);})[0]||null;}
function sentenceHtml(sentence){const tokens=state.tokens.filter(t=>t.sentence_id===sentence.id).sort((a,b)=>a.token_index-b.token_index);if(!tokens.length)return esc(sentence.text);let cursor=0,out='';for(const token of tokens){out+=esc(sentence.text.slice(cursor,token.start_offset));const occurrence=tokenOccurrence(token.id),concept=conceptOf(occurrence),phrase=concept?.kind==='phrase',saved=concept&&state.savedConceptIds.has(concept.id),suppressed=phrase&&!saved;const classes=['reader-token',saved?(phrase?'saved-phrase':'saved-word'):'',suppressed?'phrase-owned':'',state.activeOccurrenceId===occurrence?.id?'active-lexical':''].filter(Boolean).join(' ');out+=`<span class="${classes}" data-token-id="${token.id}" data-occurrence-id="${occurrence?.id||''}">${esc(token.surface)}</span>`;cursor=token.end_offset;}return out+esc(sentence.text.slice(cursor));}
function renderReader(){show('student-reader');$('#student-reader').innerHTML=`<div class="reader-shell"><div class="backline"><button class="button quiet small" type="button" data-exit-study>← Home</button></div><p class="eyebrow">PASSAGE</p><h1>${esc(state.passage.title)}</h1><p class="reader-hint">단어를 누르면 뜻을 볼 수 있어요. 문장은 두 번 누르거나 길게 누르면 분석을 볼 수 있어요.</p><article class="reading-passage">${state.sentences.map(sentence=>`<span class="reading-sentence ${state.savedSentenceIds.has(sentence.id)?'saved-sentence':''}" data-sentence-id="${sentence.id}">${sentenceHtml(sentence)}</span> `).join('')}</article></div>`;}
function cacheIndexKey(passageId){return `${CACHE_INDEX}${state.student?.id}:${passageId}`;}
function cachedPassage(passageId){try{const pointer=JSON.parse(localStorage.getItem(cacheIndexKey(passageId))||'null');return pointer?.key?JSON.parse(localStorage.getItem(pointer.key)||'null'):null;}catch{return null;}}
function cachePassage(data){try{const revision=[data.passage.id,data.passage.updated_at||'current',data.passage.bake_status||'unbaked'].join(':');const key=`ready-passage-cache-v1:${state.student.id}:${revision}`;localStorage.setItem(key,JSON.stringify(data));localStorage.setItem(cacheIndexKey(data.passage.id),JSON.stringify({key,revision}));}catch{/* disposable acceleration only */}}
function applyPassage(data){Object.assign(state,{passage:data.passage,sentences:data.sentences||[],tokens:data.tokens||[],sentenceBakes:data.sentenceBakes||[],occurrences:data.occurrences||[],savedConceptIds:new Set(data.savedConceptIds||[]),savedSentenceIds:new Set(data.savedSentenceIds||[]),activeOccurrenceId:null});}
async function openPassageStudy(passageId){if(!state.scope)return;const cached=cachedPassage(passageId);if(cached){applyPassage(cached);renderReader();}const data=await safely(()=>cached?readyApi('student_passage',{examId:state.scope.id,passageId},state.token):call('student_passage',{examId:state.scope.id,passageId},state.token,'지문을 준비하는 중…'));if(!data)return;if(!cached||JSON.stringify(data)!==JSON.stringify(cached)){applyPassage(data);renderReader();}cachePassage(data);localStorage.setItem(`ready-last-passage:${state.student.id}:${state.scope.id}`,passageId);}
function openSheet(kind,html){$('#learning-sheet-content').innerHTML=html;$('#learning-sheet').classList.add('on');$('#learning-sheet').setAttribute('aria-hidden','false');$('#learning-sheet').dataset.kind=kind;}
function closeSheet(){state.activeOccurrenceId=null;$('#learning-sheet').classList.remove('on');$('#learning-sheet').setAttribute('aria-hidden','true');if(state.passage&&!$('#student-reader').hidden)renderReader();}
function lexicalSheet(occurrence,surface){const c=conceptOf(occurrence);if(!c)return `<p class="eyebrow">DICTIONARY</p><h2>${esc(surface)}</h2><p class="study-meaning">사전 정보를 준비하고 있어요.</p>`;const choices=[{conceptKey:c.concept_key,meaning:c.context_meaning,recommended:true},...(c.alternative_senses||[])],saved=state.savedConceptIds.has(c.id);return `<p class="eyebrow">${c.kind==='phrase'?'PHRASE':'WORD'}</p><h2>${esc(c.canonical_form)}</h2><p class="study-source">${esc(occurrence.surface_text||surface)}</p><form id="save-lexical-form" data-occurrence-id="${occurrence.id}"><div class="sense-list">${choices.map((item,index)=>`<label class="sense-option"><input type="radio" name="conceptKey" value="${esc(item.conceptKey)}" ${index===0?'checked':''} ${saved?'disabled':''}><span>${item.recommended?'추천 뜻 · ':''}${esc(item.meaning)}</span></label>`).join('')}</div><button class="button primary" type="submit" ${saved?'disabled':''}>${saved?'저장됨':'저장'}</button></form>`;}
async function openLexical(token){const occurrenceId=token.dataset.occurrenceId||'',sentenceId=token.closest('[data-sentence-id]')?.dataset.sentenceId,occurrence=state.occurrences.find(item=>item.id===occurrenceId);state.activeOccurrenceId=occurrenceId||null;renderReader();openSheet('lexical',lexicalSheet(occurrence,token.textContent));record('word_lookup',{examId:state.scope.id,passageId:state.passage.id,sentenceId,occurrenceId:occurrenceId||undefined,word:token.textContent});if(occurrence)return;try{const data=await readyApi('word_lookup',{examId:state.scope.id,passageId:state.passage.id,sentenceId,word:token.textContent},state.token);if($('#learning-sheet').dataset.kind==='lexical')openSheet('lexical',`<p class="eyebrow">DICTIONARY</p><h2>${esc(data.word)}</h2><p class="study-meaning">${esc(data.meaning)}</p>`);}catch{/* sheet stays usable */}}
function sentenceSheet(sentenceId){const sentence=state.sentences.find(item=>item.id===sentenceId),bake=state.sentenceBakes.find(item=>item.sentence_id===sentenceId)||{},saved=state.savedSentenceIds.has(sentenceId);if(!sentence)return '';return `<p class="eyebrow">SENTENCE</p><h2 class="sheet-sentence">${esc(sentence.text)}</h2><section class="sheet-section"><h3>해석</h3><p>${esc(sentence.translation||'해석을 준비하고 있어요.')}</p></section><section class="sheet-section"><h3>문장 구조</h3><p>${esc(bake.structure_summary||'아직 분석되지 않았습니다.')}</p></section><section class="sheet-section"><h3>핵심 문법</h3><ul>${(bake.grammar_points||[]).map(v=>`<li>${esc(v)}</li>`).join('')||'<li>아직 분석되지 않았습니다.</li>'}</ul></section><section class="sheet-section"><h3>핵심 표현</h3><ul>${(bake.key_expressions||[]).map(v=>`<li>${esc(v)}</li>`).join('')||'<li>아직 분석되지 않았습니다.</li>'}</ul></section><button class="button primary" type="button" data-save-sentence="${sentenceId}" ${saved?'disabled':''}>${saved?'저장됨':'문장 저장'}</button>`;}
function openSentence(sentenceEl){const sentenceId=sentenceEl.dataset.sentenceId;openSheet('sentence',sentenceSheet(sentenceId));record('translation_view',{examId:state.scope.id,passageId:state.passage.id,sentenceId});}
async function openLibrary(kind='words'){const data=state.library||await safely(()=>call('personal_library',{},state.token,'복습 항목을 불러오는 중…'));if(!data)return;state.library=data;show('student-library');const words=kind!=='sentences',items=words?(data.lexical||[]).map(item=>{const concept=conceptOf(item);return `<div class="review-row"><span><strong>${esc(concept?.canonical_form||'')}</strong><small>${esc(item.meaning_snapshot||'')}</small></span><em>${esc([...new Set((item.sources||[]).map(s=>s.passage?.title).filter(Boolean))][0]||'')}</em></div>`}).join(''):(data.sentences||[]).map(item=>`<div class="review-row sentence-review"><span><strong>${esc(item.source_text_snapshot)}</strong><small>${esc(item.translation_snapshot)}</small></span><em>${esc(item.passage?.title||'')}</em></div>`).join('');$('#student-library').innerHTML=`<div class="review-head"><span>Review</span></div><div class="home-tabs review-tabs" role="tablist"><button type="button" data-library="words" class="${words?'active':''}">단어·숙어</button><button type="button" data-library="sentences" class="${!words?'active':''}">문장</button></div><div class="review-list">${items||'<div class="empty scope-empty"><strong>아직 저장한 항목이 없습니다.</strong></div>'}</div>`;}
function optimisticSaveLexical(form){const occurrenceId=form.dataset.occurrenceId,occurrence=state.occurrences.find(item=>item.id===occurrenceId),concept=conceptOf(occurrence);if(!concept)return;state.savedConceptIds.add(concept.id);form.querySelector('button').disabled=true;form.querySelector('button').textContent='저장됨';renderReader();toast('저장했습니다.');readyApi('save_lexical',{examId:state.scope.id,passageId:state.passage.id,occurrenceId,conceptKey:new FormData(form).get('conceptKey')},state.token).catch(()=>{state.savedConceptIds.delete(concept.id);if(!$('#student-reader').hidden)renderReader();toast('저장하지 못했습니다. 다시 시도해주세요.',3600);});}
function optimisticSaveSentence(button){const sentenceId=button.dataset.saveSentence;state.savedSentenceIds.add(sentenceId);button.disabled=true;button.textContent='저장됨';renderReader();toast('저장했습니다.');readyApi('save_sentence',{examId:state.scope.id,passageId:state.passage.id,sentenceId},state.token).catch(()=>{state.savedSentenceIds.delete(sentenceId);if(!$('#student-reader').hidden)renderReader();toast('저장하지 못했습니다. 다시 시도해주세요.',3600);});}
async function logout(){if(state.token)record('logout');clearSession();await chooseStudent();}

document.addEventListener('click',event=>{const button=event.target.closest('button');if(button?.id==='theme-toggle')return theme(document.body.classList.contains('dark')?'light':'dark');if(button?.id==='logout')return logout();if(button?.dataset.studentId)return openPin({id:button.dataset.studentId,name:button.dataset.studentName});if(button?.hasAttribute('data-back-students'))return chooseStudent();if(button?.dataset.startPassage)return openPassageStudy(button.dataset.startPassage);if(button?.hasAttribute('data-exit-study')||button?.dataset.studentRoute==='passages')return renderScope();if(button?.dataset.studentRoute==='review')return openLibrary();if(button?.dataset.library)return openLibrary(button.dataset.library);if(button?.hasAttribute('data-close-learning-sheet'))return closeSheet();if(button?.dataset.saveSentence)return optimisticSaveSentence(button);});
document.addEventListener('click',event=>{if(matchMedia('(pointer:coarse)').matches)return;const token=event.target.closest('.reader-token');clearTimeout(wordTimer);if(token)wordTimer=setTimeout(()=>openLexical(token),280);});
document.addEventListener('dblclick',event=>{const sentence=event.target.closest('.reading-sentence');if(!sentence)return;clearTimeout(wordTimer);event.preventDefault();getSelection()?.removeAllRanges();openSentence(sentence);});
document.addEventListener('pointerdown',event=>{if(!matchMedia('(pointer:coarse)').matches)return;const sentence=event.target.closest('.reading-sentence');if(!sentence)return;holdStart={x:event.clientX,y:event.clientY,sentence,fired:false};clearTimeout(holdTimer);holdTimer=setTimeout(()=>{if(!holdStart)return;holdStart.fired=true;getSelection()?.removeAllRanges();openSentence(sentence);},700);});
document.addEventListener('pointermove',event=>{if(holdStart&&Math.hypot(event.clientX-holdStart.x,event.clientY-holdStart.y)>12){clearTimeout(holdTimer);holdStart=null;}});
document.addEventListener('pointerup',event=>{if(!matchMedia('(pointer:coarse)').matches)return;const token=event.target.closest('.reader-token'),fired=holdStart?.fired;clearTimeout(holdTimer);holdStart=null;if(!fired&&token)openLexical(token);});
document.addEventListener('selectstart',event=>{if(matchMedia('(pointer:coarse)').matches&&event.target.closest('.reading-passage'))event.preventDefault();});document.addEventListener('contextmenu',event=>{if(event.target.closest('.reading-passage'))event.preventDefault();});
document.addEventListener('submit',event=>{event.preventDefault();if(event.target.id==='pin-form')return login(event.target);if(event.target.id==='save-lexical-form')optimisticSaveLexical(event.target);});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeSheet();});
theme(localStorage.getItem('ready-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));try{const previous=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');if(previous?.token){state.token=previous.token;loadDashboard();}else chooseStudent();}catch{chooseStudent();}
