"""Read-only candidate validation. Never opens credentials, signs, or uploads to Play."""
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import xml.etree.ElementTree as ET
import zipfile

ROOT = Path(__file__).resolve().parent.parent
BASE = 'b55f3df241607c95855a53009aceaa903e1da164'
OUT = Path('/tmp/breeze-android-candidate')
AAB = ROOT / 'android/app/build/outputs/bundle/release/app-release.aab'
ANDROID = '{http://schemas.android.com/apk/res/android}'
sha = lambda data: hashlib.sha256(data).hexdigest()
git = lambda *args: subprocess.check_output(['git', *args], cwd=ROOT)

manifest = ET.parse(OUT / 'AndroidManifest.xml').getroot()
assert manifest.attrib['package'] == 'kr.io.breeze.app'
assert manifest.attrib[ANDROID + 'versionName'] == '1.9.1'
assert manifest.attrib[ANDROID + 'versionCode'] == '1'
sdk = manifest.find('uses-sdk')
assert sdk.attrib[ANDROID + 'minSdkVersion'] == '24'
assert sdk.attrib[ANDROID + 'targetSdkVersion'] == '36'
permissions = [node.attrib[ANDROID + 'name'] for node in manifest.findall('uses-permission')]
assert 'android.permission.INTERNET' in permissions
assert set(permissions) <= {'android.permission.INTERNET', 'kr.io.breeze.app.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION'}, permissions
application = manifest.find('application')
assert application.attrib[ANDROID + 'allowBackup'] == 'false'
assert application.attrib[ANDROID + 'usesCleartextTraffic'] == 'false'
signature_result = (OUT / 'signature-verification.txt').read_text()
assert 'jar is unsigned' in signature_result

changed = git('diff', '--name-only', BASE, 'HEAD').decode().splitlines()
assert set(changed) == {'android/app/build.gradle', '.github/workflows/android-candidate.yml', 'tools/verify-android-candidate.py'}, changed
original = git('show', BASE + ':android/app/build.gradle')
candidate = (ROOT / 'android/app/build.gradle').read_bytes()
assert candidate.replace(b'versionName "1.9.1"', b'versionName appVersion') == original
generated_changes = git('diff', '--name-only').decode().splitlines()
assert set(generated_changes) <= {'android/capacitor.settings.gradle'}, generated_changes
if generated_changes:
    locator = (ROOT / 'android/capacitor.settings.gradle').read_text()
    assert locator == "// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME \"capacitor update\" IS RUN\ninclude ':capacitor-android'\nproject(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')\n"

assets = []
with zipfile.ZipFile(AAB) as archive:
    names = archive.namelist()
    assert not any(re.match(r'META-INF/[^/]+\.(SF|RSA|DSA|EC)$', name, re.I) for name in names)
    assert archive.testzip() is None
    for path in sorted((ROOT / 'www').rglob('*')):
        if not path.is_file():
            continue
        relative = path.relative_to(ROOT / 'www').as_posix()
        data = path.read_bytes()
        assert archive.read('base/assets/public/' + relative) == data, relative
        source = ROOT / relative
        assert source.is_file(), 'No tracked source for bundled web asset: ' + relative
        assert git('show', BASE + ':' + relative) == data, 'Base web source changed: ' + relative
        assets.append({'file': relative, 'sha256': sha(data), 'bytes': len(data)})
assert len(assets) > 50

tests = list((ROOT / 'android/app/build/test-results/testReleaseUnitTest').glob('TEST-*.xml'))
assert tests
totals = {'tests': 0, 'failures': 0, 'errors': 0, 'skipped': 0}
for path in tests:
    suite = ET.parse(path).getroot()
    for key in totals:
        totals[key] += int(suite.attrib.get(key, 0))
assert totals['tests'] > 0 and totals['failures'] == totals['errors'] == totals['skipped'] == 0
lint = ET.parse(ROOT / 'android/app/build/reports/lint-results-release.xml').getroot()
issues = [{'id': node.attrib['id'], 'severity': node.attrib['severity']} for node in lint.findall('issue')]
assert not any(issue['severity'] in ['Fatal', 'Error'] for issue in issues)
destination = OUT / 'breeze-android-1.9.1-code1-unsigned.aab'
shutil.copyfile(AAB, destination)
report = {
    'baseMainSha': BASE, 'candidateBuildSha': git('rev-parse', 'HEAD').decode().strip(),
    'changedPaths': changed, 'syncGeneratedLocatorChanges': generated_changes, 'nativeVersionOverride': 'android/app/build.gradle: versionName appVersion -> versionName "1.9.1"; explicit -PandroidVersionCode=1',
    'applicationId': 'kr.io.breeze.app', 'versionName': '1.9.1', 'versionCode': 1,
    'minSdk': 24, 'targetSdk': 36, 'compileSdk': 36, 'permissions': permissions,
    'file': destination.name, 'bytes': AAB.stat().st_size, 'sha256': sha(AAB.read_bytes()),
    'unsigned': True, 'bundletoolValidation': 'passed with official bundletool 1.18.3 and verified SHA256',
    'unitTests': totals, 'lintIssues': issues, 'bundledWebFiles': len(assets),
    'baseWebBytesEqual': True, 'packagedWebBytesEqual': True, 'assets': assets,
    'macAccessed': False, 'privateKeyAccessed': False, 'newKeysGeneratedByThisWorkflow': False,
    'signingConfigured': False, 'playUploaded': False, 'productionPublished': False,
    'remaining': ['Existing approved upload-key cloud signing and public certificate fingerprint matching', 'Signed bundle hash/version revalidation', 'Play internal-track acceptance and device QA'],
}
(OUT / 'android-candidate-provenance.json').write_text(json.dumps(report, indent=2) + '\n')
print(json.dumps({key: value for key, value in report.items() if key != 'assets'}, indent=2))
